### ISSUE TITLE
Implement the country profile pages

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#10]
[Link to mockup](https://design.ooni.io/mockups/explorer/screen/03270981-207b-4a23-a289-868cf2188ea5/Country-Page/)

What needs to happen here:

* [x] Implement missing API endpoints: https://github.com/ooni/api/pull/77

* [x] Implement or select a table component suitable for our use case

* [x] Implement charts for country page
- Bar chart for "types of blocked websites"
- Sparkline for "Measurements by test class"
- Websites chart

**Comment by gabelula** [comment]
All this other issues need to be completed before implementation: 

* [ ] Write up questions https://github.com/ooni/explorer/issues/24
* [ ] Wireframes https://github.com/ooni/explorer/issues/26
* [ ] User testing https://github.com/ooni/explorer/issues/27
* [ ] Mocks https://github.com/ooni/explorer/issues/28

**Comment by gabelula** [comment]
Related to https://github.com/ooni/explorer/issues/2

**Comment by hellais** [comment]
This is done as in it's ready for beta review.
