### ISSUE TITLE
Links in censorship changes section are styled inconsistently

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#100]
The links in the Censorship Changes are not styled using the styles from the `<Link>` component.

![Screenshot 2019-05-02 at 12 28 38](https://user-images.githubusercontent.com/424620/57069807-eeb23100-6cd5-11e9-8df8-ccf93799aeaa.png)

I suspect it may be needed to override the markdown component element for an `<a>`.

**Comment by sarathms** [comment]
Fixed in #141
