### ISSUE TITLE
Some font sizes are too big

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#102]
In some pages I get the impression the font sizes are way too big and disproportionate compared to the rest of the content.

Examples:

![Screenshot 2019-05-02 at 12 43 10](https://user-images.githubusercontent.com/424620/57070620-4f426d80-6cd8-11e9-974c-2f3d38ed8eba.png)
![Screenshot 2019-05-02 at 12 44 53](https://user-images.githubusercontent.com/424620/57070608-481b5f80-6cd8-11e9-83ed-579aa96f4f6f.png)

**Comment by hellais** [comment]
cc @holantonela @elioqoshi

**Comment by holantonela** [comment]
I think both blocks have the right font-size. It gives hierarchy compared with the entire content and looks very nice. 

We could improve the community facts section by adding a call to action to download the apps and adding an illustration. What do you think?

**Comment by hellais** [comment]
> We could improve the community facts section by adding a call to action to download the apps and adding an illustration. What do you think?

What is the community facts section?

**Comment by holantonela** [comment]
> What is the community facts section?

The block which contains "Thanks to OONI Probe users..."

**Comment by hellais** [comment]
Ah ok I see. 

I think one thing to consider to improve this section is perhaps making the numbers in there and the variable bits of that section more visible (like the network and measurement count).

I do still wonder if this information wasn't better suited to live inside of the hero and not be duplicated as text in here.

**Comment by hellais** [comment]
I made some tweaks to the font sizes in: https://github.com/ooni/explorer/pull/221.

You can see the difference between the two here:
![Screenshot 2019-07-19 at 12 46 57](https://user-images.githubusercontent.com/424620/61530140-872d9700-aa23-11e9-82ce-297f947004f0.png)

I was also trying to style the text inside of the `SummaryText` component, but I suspect it's not something that is immediate to do.

In particular I could not fully understand how this bit of code worked:
https://github.com/ooni/explorer/blob/master/components/measurement/SummaryText.js#L21

and why it needs to support passing in something which is either a string or func or node.

**Comment by sarathms** [comment]
Fixed in #221
