### ISSUE TITLE
The vanilla_tor section should show a zero state (or not displayed) when data is missing

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#105]
For example if I go to https://explorer-beta.ooni.io/country/BF, which has no vanilla_tor measurements I still see that section saying that there is a measurement from "a few seconds ago", yet the row is not clickable.

![Screenshot 2019-05-02 at 12 56 16](https://user-images.githubusercontent.com/424620/57071103-b44a9300-6cd9-11e9-8e59-16429b9f3135.png)

**Comment by hellais** [comment]
cc @holantonela @elioqoshi

**Comment by sarathms** [comment]
As of now, I have removed the **`Last tested`** label and the toggle button when the stats are empty.

![image](https://user-images.githubusercontent.com/700829/60684927-57509200-9e6e-11e9-9f13-1275e36f6fb8.png)

But even when there is data, we haven't really done anything to the layout of the content. Here's what we have. @holantonela any suggestions how we can present this information?

![image](https://user-images.githubusercontent.com/700829/60685544-a64bf680-9e71-11e9-9eeb-9816c798083f.png)

**Comment by holantonela** [comment]
As I suggested in #174, `0/8 Networks` header is confusing. We could have `8 Tested Networks`, instead. 

The AS number should link to the results of a search query that looks for that ASN, timeline, and test type.

[Based on the original mockup](https://www.figma.com/file/JNYZCnvn7DizbhKv0vDF4s/Explorer-Country-Pages-(Copy)?node-id=296%3A1786), you can re-use the same line graphs. @hellais what do you think?

**Comment by hellais** [comment]
Quick mock of the layout for the vanilla tor page:
<img width="660" alt="Screenshot 2019-07-13 at 15 57 15" src="https://user-images.githubusercontent.com/424620/61172614-f1a78880-a586-11e9-8925-ffdad7db56ad.png">

It should use the style of the network section.
