### ISSUE TITLE
Replace FAQ link with a data license link

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#107]
Currently in the footer we have an FAQ item which points to nothing.

We should instead relabel it as "Data License" and have it link to here: https://github.com/ooni/license/tree/master/data.

**Comment by hellais** [comment]
@agrabeli what do you think?

**Comment by agrabeli** [comment]
@hellais yes, I think that's a good solution for the time being (and we can later change it to "FAQ", once that's published).

**Comment by hellais** [comment]
@agrabeli I think that we should probably always have a link to the data license, but yeah let's evaluate where and if it makes sense to include a FAQ link once we have one.

**Comment by sarathms** [comment]
Fixed in #158
