### ISSUE TITLE
Highlights - Remove country names

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#108]
Since all of the reports included in the Highlights section start with country names, perhaps we can omit including the country names next to their respective flags, to avoid having country names displayed twice.

![highlights](https://user-images.githubusercontent.com/8290574/57084914-78c0c080-6cfb-11e9-8884-af3d14324642.png)

For example, the "Cuba highlight" would say "Cuba 2019 constitutional referendum" next to the Cuban flag.

**Comment by sarathms** [comment]
It is a simple change. But I think we should then rearrange the elements for better use of space. The first row will have only the flag, while second one has a title and two buttons, adding constraints to how long the title can be. In which case, we should do it post-beta. cc: @elioqoshi @holantonela

**Comment by holantonela** [comment]
We can easily make it done for beta by removing `countryName` at highlights.json as suggested at
https://github.com/ooni/explorer/issues/109#issuecomment-488756985

**Comment by agrabeli** [comment]
I have addressed this via this pull request: https://github.com/ooni/explorer/pull/140
