### ISSUE TITLE
Highlights - Make Explore links consistent

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#109]
The "Explore" link for Cuba (under the "censorship during political events" section) points to the OONI Explorer page for tremendanota.com (one of the sites blocked, as noted as part of that report/highlight). All the other "Explore" links though point to the canonical country pages on OONI Explorer. 

Do we want to point to the Explorer country pages, or do we want to point to the specific Explorer pages pertaining to the specific findings? We probably need to pick one and make it consistent across "Explore" links.

@hellais thoughts?

**Comment by sarathms** [comment]
As discussed, please edit the [highlights.json](https://github.com/ooni/explorer/blob/master/components/landing/highlights.json) file which is used to render the highlights section.

**Comment by agrabeli** [comment]
I have addressed this via this PR: https://github.com/ooni/explorer/pull/140

**Comment by sarathms** [comment]
This is done.
