### ISSUE TITLE
Display countries alphabetically based on country names

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#111]
Currently the countries on the Countries page are not listed alphabetically based on the country names, but based on the country codes. It may therefore be confusing that Chad, for example, is listed towards the end of the list (because of its TD country code), instead of next to other countries whose names start with a "C". 

I'd like to propose that the countries are listed alphabetically based on country names (instead of country codes).

**Comment by hellais** [comment]
This is fixed via: https://github.com/ooni/explorer/pull/166
