### ISSUE TITLE
Search page - Fix colour coding of side-bar based on results

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#112]
When you go to the Search page and view All Results, the side bar for all Web Connectivity results is always orange (hinting that the measurements are anomalous), regardless of the actual results of individual measurements.

For example, in Benin, all results are displayed orange: http://explorer-beta.ooni.io/search?probe_cc=BJ&test_name=web_connectivity&only=all 

![benin-orange](https://user-images.githubusercontent.com/8290574/57090776-d824cd80-6d07-11e9-901c-4f526136e8a6.png)

... but if you click on the measurements, you will see that some are accessible (for example: http://explorer-beta.ooni.io/measurement/20190501T233600Z_AS37424_IoD9FYL8BbUCr1L3gAqiivhdfeVDDAD3uyfCbbJAZL1k2MNbgW?input=http://www.gmhc.org/). 

We therefore need to fix the colour-coding of the side bar to display colours depending on the results (green for accessible, orange for anomaly, yellow for error, red for confirmed blocked).

**Comment by sarathms** [comment]
Similar to #113

**Comment by hellais** [comment]
We now opted for the tradeoff of showing those all as green, though there may be some that are actually failed.

We currently can't do much without touching the pipeline.

I suggest we close this issue and keep #113 open to remind ourselves to test it when pipeline fixes are rolled out.
