### ISSUE TITLE
Confirmed on Search page: Move "Results not found" & delete "Load more" button

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#117]
When a country doesn't have any confirmed cases of blocking (which is most countries), the user sees this:

![confirmed-page](https://user-images.githubusercontent.com/8290574/57091814-4e2a3400-6d0a-11e9-9394-4761d40a6048.png)

I propose:

1. Moving "No results found" down, onto the white space (after the legends), so that it can be more visible.

2. Deleting the "Load more" button (since there is nothing to load in this case).

**Comment by holantonela** [comment]
I agreed. Do we have an empty/no-found illustration from Probe to place there?
