### ISSUE TITLE
Display IM test status bigger in banner

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#119]
When you land on the measurement pages for IM tests (e.g. WhatsApp test), the subtitle (in the banner) that communicates whether the specific app is blocked or not is displayed in extremely small writing. For example, "WhatsApp is accessible":

![whatsapp-accessible](https://user-images.githubusercontent.com/8290574/57093403-1a510d80-6d0e-11e9-9009-07b61de5f733.png)

It would be great if "WhatsApp is accessible" was bigger (same for Telegram & Facebook Messenger tests), so that the user could view it quickly/easily at first glance.

**Comment by holantonela** [comment]
yes, this should follow the same H style we have on the Web Connectivity Test Measurement page, like http://explorer-beta.ooni.io/measurement/20190503T002824Z_AS3320_WEIDLeodeoBtJbFNGtubKswQcr3Chy6HU7Iu5PV6n7vhjbQIjl?input=http://www.xenu.net/
