### ISSUE TITLE
Update country pages with published OONI research reports

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#122]
How will the published OONI research reports be added to the "Research Reports" section of country pages? Will this somehow be automatically updated, or will we need to manually edit this section when relevant reports are published?

Yesterday we published a report on Benin, but it doesn't appear in the Benin country page: http://explorer-beta.ooni.io/country/BJ

On ooni-web, we added "benin" as a tag in the PR for this report: https://github.com/TheTorProject/ooni-web/pull/263/files

Perhaps this section can automatically be updated by searching the country tags allocated to posts published via ooni-web?

**Comment by hellais** [comment]
With @sarathms we were discussing maybe choosing a particular tag that we could use to identify reports relevant to a particular country.

Maybe we could use the tag `report` and then have a tag which says `country-XX` where `XX` is the two letter country code that report is about?

**Comment by agrabeli** [comment]
@hellais @sarathms The tags added as part of PRs https://github.com/TheTorProject/ooni-web/pull/270 and https://github.com/TheTorProject/ooni-web/pull/228 will help with importing relevant research reports in (the new) OONI Explorer country pages.

The tag, in particular, that you need to look out for is: "country-xx" (where "xx" is the relevant country code).
