### ISSUE TITLE
Fix flags

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#125]
Some countries appear to have wrong flags... for example, Italy:

![it-flag](https://user-images.githubusercontent.com/8290574/57096052-9b130800-6d14-11e9-8897-4dc57695b728.png)

**Comment by hellais** [comment]
I believe this is some odd edge case that happens when you apply a filter on the country listing.

**Comment by sarathms** [comment]
I am unable to reproduce this. What filter did you apply?

**Comment by hellais** [comment]
@sarathms it happens when you apply some filtering to the page and it has just loaded.

**Comment by sarathms** [comment]
I am able to see this, at least once, on Firefox too. This needs a more fundamental relook at how we build and load the flags. Needs more debugging.

**Comment by sarathms** [comment]
Unable to reproduce this now on any browser. @hellais Can you help debug this?

**Comment by hellais** [comment]
Yeah I can't reproduce it either anymore. I say we close it
