### ISSUE TITLE
Display tested URLs separately from "Web Connectivity"

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#127]
In the Search page, when the tested URLs are displayed in the same column, right on top of "Web Connectivity", it looks too cluttered and you can barely read which URL has been tested (which is the main information we're interested in).

![web-connectivity-clutter](https://user-images.githubusercontent.com/8290574/57096556-e11c9b80-6d15-11e9-8fa2-cf3be53ccf71.png)

I therefore propose that we separate the two, displaying the tested URL and "Web Connectivity" in separate columns (or deleting "Web Connectivity" entirely if there's no space for an extra "column").

**Comment by holantonela** [comment]
It is done. Looks good!
![Screenshot_2019-06-06 Search Measurements - OONI Explorer](https://user-images.githubusercontent.com/7602174/59032388-91f9e700-883c-11e9-84e0-d697e269e9d8.png)
