### ISSUE TITLE
Display selected Heading in country pages

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#128]
If I'm on a country page and select one of the sections (e.g. Networks) from the menu on the left, the heading (Networks) is not displayed on the top of the page:

![network-without-header](https://user-images.githubusercontent.com/8290574/57097640-820c5600-6d18-11e9-8164-7ccb938fac47.png)

I should probably see this instead:

![network-with-header](https://user-images.githubusercontent.com/8290574/57097646-8a649100-6d18-11e9-8131-060f874fd103.png)

**Comment by holantonela** [comment]
Related with #71. We should have it fixed if we implement some of the options we suggested there.

**Comment by hellais** [comment]
This is now fixed by having a sticky navbar.

<img width="1342" alt="Screenshot 2019-07-30 at 12 09 57" src="https://user-images.githubusercontent.com/424620/62146230-f7a9a300-b2c2-11e9-93dc-82386c930755.png">
