### ISSUE TITLE
Remove "Load More" button when maximum amount of measurements displayed

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#129]
When filtering measurements based on a specific date range (in Guatemala, for example), I only get a limited set of measurements, yet the "Load More" button is still displayed (but since we only have 1 measurement in this case, clicking on the "Load More" button wouldn't work).

![filter-dates](https://user-images.githubusercontent.com/8290574/57097859-11b20480-6d19-11e9-80b2-6b20c2f38e76.png)

We therefore need to remove the "Load More" button if the maximum amount of measurements is already displayed.

**Comment by sarathms** [comment]
@agrabeli Try this link to see if it works as expected now. http://explorer-beta.ooni.io/search?probe_cc=UZ&since=2019-05-15&test_name=web_connectivity&until=2019-05-31
