### ISSUE TITLE
Error occurs after a few filtered searches

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#130]
After a few filtered searches on the Search page, I get an error:

![error-page](https://user-images.githubusercontent.com/8290574/57098163-baf8fa80-6d19-11e9-98b6-39e30cf68774.png)

The first few searches work well, but after a few, this error appears, regardless of the type of search. This leads me to think that perhaps this is an issue on the pipeline? Limited ability to perform search functions...?

**Comment by sarathms** [comment]
Cannot reproduce this anymore. This must have gotten fixed after the improvements made to pipeline and API took effect. @agrabeli Please check if you still face difficulty operating the search page.

**Comment by hellais** [comment]
Yeah I think this is old at this point. @agrabeli if you notice similar issues again please file a new issue.
