### ISSUE TITLE
Remove "In a nutshell" section & add it once we have better heuristics

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#134]
The "In a nutshell" section on country pages is great for providing an overview of results. 

In practice though, it's currently not super useful and can be quite misleading, due to limitations to our current heuristics (i.e. what is processed, what is presented from the pipeline, etc.). For example, when you land on the Egypt page, it says "the blocking of websites is not confirmed" (because they don't serve blockpages), while we know as a fact that they are blocking websites (we have confirmed this through data analysis in our research reports). I imagine many people will then ask us why we say that there is no website blocking in their countries (i.e. same questions we have been getting for the current Explorer). 

I therefore propose that we drop the "in a nutshell" section (as, in most cases, it doesn't offer any particular value to the user), and only add it once/if we have better heuristics and are able to display results better / with more confidence.

**Comment by agrabeli** [comment]
Upon discussion with the team, we have decided to disable the "In a nutshell" section temporarily (and re-enable it in future releases, when we have better heuristics).

**Comment by sarathms** [comment]
@agrabeli @holantonela This is WIP and has been deployed to the beta instance for preview. I feel that the page is not being introduced the right way to a user now. Maybe we should come up with an alternative instead of hiding it, even if temporarily.
