### ISSUE TITLE
Filter results should be greyed out when no changes are made to the filter

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#138]
![Screenshot 2019-05-03 at 19 16 45](https://user-images.githubusercontent.com/424620/57154013-11c50980-6dd8-11e9-9cb8-9f26918fadac.png)

I think it would be more usable if we made the filter result button change state to being clickable only if changes are made to the selections.

**Comment by sarathms** [comment]
This is implemented in #199. But currently blocking on ooni/design-system#58 for styling of the button's disabled state.
