### ISSUE TITLE
Review the confirmed blocked badges

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#139]
I find they look a bit odd and they don't wrap around cleanly when the URL is too long.

![Screenshot 2019-05-03 at 19 14 52](https://user-images.githubusercontent.com/424620/57154075-3e792100-6dd8-11e9-9436-6f0008a366c5.png)

**Comment by holantonela** [comment]
Why we need `Confirmed Blocked` and `Likely blocked` labels? We already have filtering categories and measurement results that refers to those situations. Is there any case that `Confirmed blocked` is not `Confirmed` and that `Likely Blocked` is not an `Anomaly`?
---
It seems like the colored left border is not enough to easily visualize the result of the measurement. Is that the problem? Could I have more background about it?

**Comment by hellais** [comment]
Confirmed blocked is for cases in which we are sure that the site is blocked. This only applies to web_connectivity test results.

**Comment by hellais** [comment]
I suggest we change this labelling to "Confirmed" and show a tooltip on hover that say "Website confirmed to be blocked".

We can display a similar tooltip on the search filter label.

@agrabeli what do you think?

**Comment by agrabeli** [comment]
@hellais Ideally it would say "Confirmed blocked", as I suspect that not everyone will hover over it to learn what is confirmed. How about we say "Confirmed blocked" in the legend, and just "Confirmed" in the button?

That way, it would be consistent enough (since it's quite clear what it's referring to since "blocked" is mentioned in the legend), and as inconsistent as "Anomalies" (legend) and "Anomaly" (button displayed on measurement).

**Comment by sarathms** [comment]
Copy has been updated to show 'Confirmed' in the badge.

**Comment by holantonela** [comment]
> I suggest we change this labelling to "Confirmed" and show a tooltip on hover that say "Website confirmed to be blocked".

Confirmed label looks ok. I like the tooltip idea, not sure how it will expand coherently to other scenarios, though. Do we want to have tooltips for all "Confirmed" labels?

**Comment by hellais** [comment]
> Do we want to have tooltips for all "Confirmed" labels?

Yes I suggest that as we add heuristics for "confirming" more types of tests the tooltip will say different things depending on the type of test.

The tooltip on the filter/search sidebar will OTOH include information about all the possible scenarios.

**Comment by holantonela** [comment]
> Yes I suggest that as we add heuristics for "confirming" more types of tests the tooltip will say different things depending on the type of test.

Cool. I created #252 for following that work. I think we are done here, then.
