### ISSUE TITLE
Add translation support

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#14]
We should use a similar pattern (and the same library) we use in probe-desktop: https://github.com/ooni/probe-desktop/blob/master/renderer/components/withIntl.js.

However two main differences need to be taken into account:

1. We don't want to have to specify all the possible strings we will use in OONI Explorer a-priori and we should rather use the pattern of putting a `<FormattedMessage defaultMessage='foo'/>` and write a string extraction script

2. We would like the strings to be translated server-side and based on the `Accept-Language` HTTP header, instead of the javascript `user.language` value, since we do server-side rendering (which we don't do in the mobile app).

For these two it's probably useful to check out the next.js react-intl example here: https://github.com/zeit/next.js/tree/canary/examples/with-react-intl (which is also what the withIntl component above was based on).

**Comment by sarathms** [comment]
Implemented in #48 and #53

**Comment by hellais** [comment]
Yes this is good. I say we close it.
