### ISSUE TITLE
Explorer and Report buttons in highlights should have hover and click effects

### ISSUE THREAD

**Issue by elioqoshi** [ooni/explorer#149]
Currently, the Explore and Report buttons in the Highlights section don't have any effect indicating that they are interactive. It would be good to add effects on hover and click changing the color of the button

![image](https://user-images.githubusercontent.com/5436686/57182697-4f8e6480-6ea2-11e9-9fa4-16093bc05ed2.png)

**Comment by sarathms** [comment]
Same as #99
