### ISSUE TITLE
Country page - Link graphs to measurements

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#150]
The graphs (under the Websites and Apps sections) on the country pages are really cool, but they're not very actionable at the moment. 

For example, when you land on the Iranian page, you see that a number of websites presented blocking in the timeline of their testing (the red bars displayed in the graph)...

![ir-blocked-sites](https://user-images.githubusercontent.com/8290574/57243046-c2801280-703d-11e9-888a-ed8b51604c7a.png)

...but when you click on the red bars, nothing happens, and you can't easily access the measurements to learn more.

I realize that the graphs present aggregates, but it would be great if the chart was more interactive. 

Specifically, it would be great if, by clicking on bars on the chart, the user is re-directed to the relevant measurements on the Search page. And it would be great if the same applied to the graphs under the Apps section as well.

**Comment by sarathms** [comment]
As per the mockup, the interactive part of these charts were in the form of stats updated on the left of the chart as we hover/click on the bars.
![image](https://user-images.githubusercontent.com/700829/57246814-31dd0e80-700c-11e9-907a-7274c116d1c3.png)

The way I understood is that the top-right button allows for one of the graphs to be maximized at a time, and make it interactive (as described above).

Do you think that would be useful or should it work differently?

**Comment by holantonela** [comment]
Hi, I think we can make some small tweaks to the current graph to achieve a more close version to the mockup. Such as:
- [ ] Add the website category icon 
- [ ] Add a [View Measurements] link to the search result page, filtered by `country` + `website` + `timelapse`
- [ ] Which period of time we are showing here? Could we render more results and reduce the space between each vertical line?

**Comment by sarathms** [comment]
>  Add the website category icon
> 
I don't think we have that capability yet. https://github.com/ooni/api/issues/85 is still open.
>  Add a [View Measurements] link to the search result page, filtered by `country` + `website` + `timelapse`
> 
This is done in #125 
>  Which period of time we are showing here? Could we render more results and reduce the space between each vertical line?
We are showing 30 days by default and had decided long back that we will first launch without the tinme period filter and then enable it later on. If we increase the default period, we have to do it across the page.

**Comment by hellais** [comment]
This looks good. We need to update the copy though because on the deployed site I only see the to be translated keyword.
