### ISSUE TITLE
Measurement pages are using wrong timestamp

### ISSUE THREAD

**Issue by holantonela** [ooni/explorer#152]
## Expected Behavior
Measurement pages excerpt should use the timestamp of the probe.

## Actual Behavior
Measurement pages excerpt are using local timestamp.

## Steps to Reproduce the Problem
Go to http://explorer-beta.ooni.io/measurement/20180101T200009Z_AS31549_2qR89L0XFMpJGVQOBtR3PKzxzpNjCs7Sh7ZErjdJGw3KFDdkP1?input=https://www.instagram.com/
![Screenshot_2019-05-07 OONI Explorer](https://user-images.githubusercontent.com/7602174/57297649-83d27280-70a6-11e9-9ee8-e35dc3e459e5.png)

**Comment by sarathms** [comment]
Looks like it was affecting only web_connectivity tests where that section was implemented differently from other tests.
