### ISSUE TITLE
Web Connectivity test status undetermined

### ISSUE THREAD

**Issue by sarathms** [ooni/explorer#154]
## Expected Behavior
Measurement page for `web_connectivity` should determine if the 'status' is `accessible`, `anomaly`, `confirmed` or `failure`. And display messages to convey the necessary details in the Hero and Summary Text areas.

## Actual Behavior
Unable to determine the status. Summary text is blank as the conditions checked are not met. The fact that all measurements currently flag `isFailure = true` in metadata, doesn't help in checking if this is indeed a failed test.

## Steps to Reproduce the Problem

  1. [This measurement](http://explorer-beta.ooni.io/measurement/20190504T152614Z_AS6830_n89RPFJzbMeQGsnxoKTMtoPg5xzUlRvguxwh7IT1F7vfcnksxE?input=http://www.radioislam.org/)

**Comment by sarathms** [comment]
Looks like it wasn't handled in the [old explorer](https://explorer.ooni.torproject.org/measurement/20190504T152614Z_AS6830_n89RPFJzbMeQGsnxoKTMtoPg5xzUlRvguxwh7IT1F7vfcnksxE?input=http:%2F%2Fwww.radioislam.org%2F) as well. @hellais Is this actually a failed test?

**Comment by hellais** [comment]
@sarathms in this case the control measurement is empty and `blocking` is `null`, so you should treat this as a failed mesurement not an anomaly.
