### ISSUE TITLE
End to End Testing Strategy for OONI Explorer

### ISSUE THREAD

**Issue by sarathms** [ooni/explorer#159]
Firstly, I think we should be able to come up with priority list of objectives to achieve using a test suite. Proposing a draft below to start with.

### Objectives
1. Ensure application builds (`yarn run build` runs successfully)
2. Ensure high level pages render without major errors (`pages/*.js`)
3. Breakages that occur when upgrading dependencies to major versions should be caught.

Are there more objectives we can think of? To what extent are the ones listed achievable? What can be tested from a UX perspective?

**Comment by hellais** [comment]
As part of this sprint we will do: https://github.com/ooni/explorer/issues/377 and then do the implementation in the future.

**Comment by hellais** [comment]
Before the next frontend call @sarathms will do some research into this and we can have a chat about the options.

**Comment by sarathms** [comment]
It appears [cypress.io](https://www.cypress.io/) is a suitable candidate to help us write high level tests. Features that I found useful:

**Comment by sarathms** [comment]
A sample implementation with cypress is available on [e2e-testing branch](https://github.com/ooni/explorer/tree/e2e-testing) for evaluation.
