### ISSUE TITLE
Long URLs in websites section on Country page

### ISSUE THREAD

**Issue by sarathms** [ooni/explorer#165]
## Expected Behavior
Long URLs should be truncated or wrapped around to the next line, especially on smaller screens.

## Actual Behavior
Overflows to the right of the page and messes up the page layout.

**Comment by sarathms** [comment]
The first one is before fix. The second one is the proposed fix. @holantonela Is there a better way to show something like long or maybe longer?

![image](https://user-images.githubusercontent.com/700829/59141155-f7052800-8975-11e9-8e04-b9c8d756e9cc.png)

**Comment by hellais** [comment]
I suggest we truncate URLs to some maximum length and if possible expand them when you hover over them.

I think that wrapping them like that can create issues especially with extremely long URls (there are URLs longer than the ones above in Explorer).

**Comment by holantonela** [comment]
I think it is relevant to expose the start and the end of the URL. Then, we can show the entire URL in an `alt` at the hover. Ideally, that URL is a link to a search query (#150)
 
For example:
`http://www.thelongurlishere123.com`
`http://www.thelo....123.com`

**Comment by sarathms** [comment]
This is yet to be done as per the last comment.

**Comment by sarathms** [comment]
Now implemented this way. Tooltip showing full URL, truncated to ~40 characters. Showing full domain and last part of the path.

![image](https://user-images.githubusercontent.com/700829/62021509-8b7d5100-b195-11e9-8d5f-0bfd1a205ec5.png)

**Comment by hellais** [comment]
This is good and it works as expected.
