### ISSUE TITLE
Link country name in measurement to country page

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#171]
When you search through measurements, it would be extremely handy if you could navigate to a country page by clicking on the country name displayed on a measurement page.

For example, in the following measurement page, it would be great if users could click on "Turkey" and get redirected to the Turkish country page.

![example](https://user-images.githubusercontent.com/8290574/58191002-5b618f80-7cc6-11e9-9c13-e24079a82f87.png)

**Comment by sarathms** [comment]
Closing as per https://github.com/ooni/explorer/issues/116#issuecomment-499896501
