### ISSUE TITLE
Improve the failed NDT measurement page with grey background

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#172]
On failed NDT measurement pages (which I keep coming across unfortunately), the word "Results" is quite big, while "Failed test" is quite tiny, and the font generally feels quite odd. For example:

![example](https://user-images.githubusercontent.com/8290574/58191406-286bcb80-7cc7-11e9-982f-53cfe51b2084.png)

Can we improve the font sizes? Perhaps remove "Results" entirely (when the NDT test fails) and only display "Failed test" (at the size that "Results" is currently in)?

It also seems that the values shared in the blue banner need to be re-aligned.

**Comment by holantonela** [comment]
Yes. Let's remove "Results" and have "Failed test" with that h1 style.

> It also seems that the values shared in the blue banner need to be re-aligned.
I asked @hellais about it and seems like the ASN name is missing and some countries have long names. That said, maybe we should open a new issue to review that part of the header.

**Comment by sarathms** [comment]
As part of #182, the font size is bigger for the 'Failed Test' text. But it doesn't replace the 'Result' label.
@holantonela Do we still want to do it? Or is the font situation better this way? 

![image](https://user-images.githubusercontent.com/700829/59127151-de285280-8934-11e9-9ee6-510fd66a301b.png)

**Comment by holantonela** [comment]
Could we remove `Results` and have `Failed test` instead?

**Comment by hellais** [comment]
I think we should implement the same layout for this test as the one used in the failed web_connectivity test results:
![](https://user-images.githubusercontent.com/7602174/59623827-9d39f600-910b-11e9-9e14-f305ad5c9df2.png)
https://github.com/ooni/explorer/pull/193#issuecomment-502776510

**Comment by hellais** [comment]
Here is a sample measurement for this: https://explorer-beta.ooni.io/measurement/20190729T143026Z_AS30873_jQmaexXwC2JNBJ9E1pXRJbCuNz7D3qUSWJcJ2Zf1d47Yv9vmLZ.

 It's still not grey the background. I am OK with us doing this post-launch.
