### ISSUE TITLE
Country pages: apps - UI adjustments

### ISSUE THREAD

**Issue by holantonela** [ooni/explorer#174]
- [x] Review the padding at the table header. "Last tested + icon" should be aligned to the right.
 ![Apps Table Header](https://user-images.githubusercontent.com/7602174/58255540-9524ab80-7d43-11e9-83de-6e1bd280f7c2.png)
- [x] The padding between each row should be reduced by 50%.
- [x] For messaging apps with less than 10 measurements should have the toggle open by default.
- [x] Each ASN per row should link to a search result for that ASN + that test query, like `/search?probe_asn=AS29032&test_name=facebook_messenger`. This will fix https://github.com/ooni/explorer/issues/150
- [ ] The bars are showing qty, we could change the color to black/darkgrey rather than green.

**Comment by hellais** [comment]
yes I agree we should make the bars in the country page for the IM tests grey as we don't derive any anomalies there yet.
