### ISSUE TITLE
TypeError: a.testName is undefined

### ISSUE THREAD

**Issue by sarathms** [ooni/explorer#176]
[Sentry logs](https://sentry.io/organizations/ooni/issues/1039603910/?project=1427510&query=is%3Aunresolved&statsPeriod=14d) indicate a recurring error for certain queries on the search page.

Example search url: https://explorer-beta.ooni.io/search?input=madamasr.com&probe_cc=EG&test_name=web_connectivity&probe_asn=AS8452

**Comment by hellais** [comment]
We should probably do tighter prop validation on the `ResultTag`.

**Comment by sarathms** [comment]
This bug isn't reproducible anymore.

**Comment by hellais** [comment]
Then I guess we can close this.
