### ISSUE TITLE
Show website is down on Web Connectivity measurement page

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#178]
Here is an example of it:
http://explorer-beta.ooni.io/measurement/20190602T034152Z_AS29032_sFjEu7kwoDsBul2dsW6Pqd5ykiAnP4fEQwoGTZVsUmAm7rwiHG?input=http://www.misseastafrica.co.uk

The value of the blocking key is `false`, so it should not be an anomaly:

```
"blocking": false
```

This may be due to the site being marked as `accessible: false`.

**Comment by hellais** [comment]
We have decided that we are going to make this page green and we will show instead of "Anomaly", "The website is down" or similar copy.

Relevant bits of code that need to be looked at:
https://github.com/ooni/explorer/blob/master/components/measurement/nettests/web_connectivity.js#L270
https://github.com/ooni/explorer/blob/master/components/measurement/nettests/web_connectivity.js#L287
https://github.com/ooni/explorer/blob/master/components/measurement/nettests/web_connectivity.js#L39

**Comment by sarathms** [comment]
This fix should be included in the related PR #193
