### ISSUE TITLE
Re-add Measurement.Hero.Status.Anomaly into Hero unit for Measurement 

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#179]
Currently the Hero Unit is missing the strings from `Measurement.Hero.Status.Anomaly.*` next to the Anomaly string.

**Comment by hellais** [comment]
@holantonela will look into making a mock to add this to that page.

The possible values are:
* DNS
* HTTPDIFF
* HTTPFAILURE
* TCPIP

**Comment by holantonela** [comment]
I made a couple of options for this idea about to including the anomaly status at the hero zone. Let's base our decision on which kind of hierarchy we would like to do at this information. IMO is very relevant but I'd not include it in the main title. What do you think is better?

1.
![4](https://user-images.githubusercontent.com/7602174/59035910-a510b500-8844-11e9-9726-1b2ce4a98956.png)
2.
![1](https://user-images.githubusercontent.com/7602174/59035058-d38d9080-8842-11e9-8558-557a69326112.png)
3.
![2](https://user-images.githubusercontent.com/7602174/59035056-d38d9080-8842-11e9-8f70-466b384152a3.png)
4.
![3](https://user-images.githubusercontent.com/7602174/59035059-d38d9080-8842-11e9-8c2f-0b78c53d96dc.png)

**Comment by sarathms** [comment]
Just wanted to link #102 here because @hellais was wondering if some more data can make it into the Hero. If we are iterating, we should probably evaluate that idea as well.

**Comment by sarathms** [comment]
@hellais I am leaning towards `2`, but I am fine with `3` or `4` too. Do you have a preference? Also see the comment above.

**Comment by hellais** [comment]
I would suggest going for 3.
The URL tested is more important than the reason for blocking.

We may also want to add next to the URL the category code in the future and I think 3 is more scalable in that direction.
