### ISSUE TITLE
Sync the master spreadsheet for strings to the latest

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#180]
This should be updated: https://docs.google.com/spreadsheets/d/1QAeDVF5wYj7bnTE6rJ0XX3C8sBF0o6A0TxeLw9fpTvM/edit#gid=0

**Comment by sarathms** [comment]
The babel plugin to extract the keys throws an error because of [this pattern](https://github.com/ooni/explorer/blob/master/components/country/overview.js#L80) which doesn't allow the plugin to statically evaluate the keys. These need to be refactored to be able to extract as expected.

**Comment by sarathms** [comment]
WIP here: https://github.com/ooni/explorer/tree/fix/extract-keys

**Comment by sarathms** [comment]
@agrabeli I have updated the missing keys from the code into the spreadsheet. They have empty values right now. I have also reset formatting on all cells.

**Comment by sarathms** [comment]
@agrabeli I have updated the missing keys from the code into the spreadsheet. They have empty values right now. I have also reset formatting on all cells. I should be able to see the changes you made when I import the csv file for integration.
