### ISSUE TITLE
Improve UX of the raw measurement data log

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#189]
I think that the orientation of the expansion collapse button on the measurement page for raw data looks a bit odd.

<img width="1327" alt="Screenshot 2019-06-08 at 13 30 51" src="https://user-images.githubusercontent.com/424620/59146708-c19e2000-89f1-11e9-8adb-62fc9151f19c.png">

Moreover it doesn't give any response when you click on it to expand it.

We should see if we can improve the UI of this.

Also is there a reason to not have the raw data expanded by default instead of requiring the user to expand them? It is at the end of the page so I don't think it should pose a problem to have it expanded by default as it is in the current explorer.

cc @holantonela

**Comment by hellais** [comment]
I have now understood what is confusing me. The `v` icon should be inverted. It should point downwards when it can be expanded, while it should point upwards when it can be collapse (i.e. the opposite to how it works now).

**Comment by sarathms** [comment]
The icons should be replaced with more appropriate `MdExpandMore` & `MdExpandLess`

**Comment by sarathms** [comment]
Using only one of the icons because we use a rotate animation.

![image](https://user-images.githubusercontent.com/700829/59225186-17afc680-8b9e-11e9-9713-ea1e2e412f00.png)

**Comment by holantonela** [comment]
That works for me, thanks @sarathms! Could we have it expanded by default? I agree with @hellais about it. 

After that, I think we can close this issue.
