### ISSUE TITLE
Reduce number of web assets at /countries

### ISSUE THREAD

**Issue by darkk** [ooni/explorer#19]
https://ooni-explorer-next.test.ooni.io/countries loads "slowly" despite being mostly static content

"Slowly" is ~10.5 seconds on 100 Mbit/s connection. That seems to be limited by number of parallel requests the browser sends to the server (six) as a query is sent for each of 256 web assert (mostly, for flags). So that's ~44 round-trips to the server to load the page. That correlates well with RTT of 200ms I have to the server. RTT-based estimation gives 8.8s as minimal page load time that's quite close to the value I actually see.

I suggest to consider converting the flags into, maybe, per-continent sprites to improve performance of the page.

**Comment by hellais** [comment]
The images on the country listing page are now lazily loaded, which leads to a much faster load time. This can now be considered closed.
