### ISSUE TITLE
Implement revamped OONI Explorer

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#2]
Canonical link to mockups: https://design.ooni.io/mockups/explorer

Attached here are the mockups.

The landing page is still WIP.

[Explorer Revamp Mockups 32.pdf](https://github.com/ooni/explorer/files/2046694/Explorer.Revamp.Mockups.32.pdf)

cc @elioqoshi

**Comment by elioqoshi** [comment]
I plan to have a landing page draft done for tomorrow

**Comment by elioqoshi** [comment]
[OONI Explorer Views Prototype v34.pdf](https://github.com/ooni/explorer/files/2071964/OONI.Explorer.Views.Prototype.v34.pdf)


PDF attached.

**Comment by elioqoshi** [comment]
Here is also the prototype on Adobe XD where you can comment on specific hotspots as well:

https://xd.adobe.com/view/5ce42d4b-386e-44dc-679e-f509e9dc1a36-2ad5/

**Comment by elioqoshi** [comment]
@sarath @hellais  you can access the specs of the views here:
https://xd.adobe.com/spec/d0d13757-52b6-49ba-5c5f-62e3e9143222-a6e0/

Might be helpful. Keep in mind that they might not be pixel perfect yet.

**Comment by hellais** [comment]
This ticket contains some useful information, that may still be relevant: https://github.com/ooni/design-system/issues/6/.

But we should use only one of the two ticket to track the progress on this to avoid confusion.

**Comment by elioqoshi** [comment]
Updated specs here: https://xd.adobe.com/spec/2f585e0f-1a7e-4f6c-41f9-fa411520998e-5969/

**Comment by hellais** [comment]
The canonical URL for the mockups is: https://design.ooni.io/mockups/explorer/

**Comment by gabelula** [comment]
This issue is already covered in all the other tickets on implementation of the different pages.
