### ISSUE TITLE
Terminate search API query if user navigates to another filter

### ISSUE THREAD

**Issue by darkk** [ooni/explorer#20]
`/search` page does not terminate API query when user switches virtual "tabs". E.g. the following screenshot was reproduced using following sequence of actions:
- open https://ooni-explorer-next.test.ooni.io/search
- wait till "all results" load
- go to "confirmed"
- wait for ~ half a second (API is currently extremely slow for that query)
- switch back to "all results", switch back and forth between "virtual tabs"
- _every_ switch spawns new API query to the backend (e.g. there are several parallel-running `anomaly=true` queries!)
- eventually error is delivered somewhere to the UI, the error may be irrelevant to the "currently open" tab as one can see below (error for anomalous query in "all results" tab):

![no-query-termination 2018-11-16 20-06-40](https://user-images.githubusercontent.com/21046/48793910-7cdac200-ed09-11e8-8c8d-1205ec2ef782.png)

Moreover, as soon as UI enters this state, "Filter results" button (with empty filter) sends valid query to the API, "loading" spinner is shown, API responds with valid response, "loading" spinner is hidden, but the response is not actually rendered (visual state looks exactly the screenshot above: error message, nothing else). Also, the error message is not hidden when the new query is issued while all pending queries are already "finished" (either correctly or failing).

"Bad UX" would just block controls till the request is received and @sarathms suggests that as a last resort. Terminating the running query is, maybe, slightly better pattern.

**Comment by hellais** [comment]
@sarathms can you confirm if this is in fact still the case or not?

**Comment by sarathms** [comment]
Since we changed the UI for the search page, this problem isn't that common anymore. When a query is in progress, the user can work the filters, but those actions don't trigger API requests until the user hits the button.

But when the button is clicked, a new API request is created while the previous one is still active. I think we should terminate the older request at this point and then start the new one.

**Comment by hellais** [comment]
This has been superseeded by https://github.com/ooni/explorer/issues/74
