### ISSUE TITLE
Improve highlights

### ISSUE THREAD

**Issue by holantonela** [ooni/explorer#200]
Besides searching, highlights listing is best feature Explorer has. We can improve the way we are displaying this section on our homepage.

Using [the data set](https://github.com/ooni/explorer/blob/master/components/landing/highlights.json), I worked in two different layouts for this section. Cards are an excellent way to show this information. We can have a carousel with tabs to navigate different sets (1), or we can have different carousels for each listing set (2).

The card background color is taking [the darkest hex](https://stackoverflow.com/questions/12043187/how-to-check-if-hex-color-is-too-black) available as a `fill` in the flag.svg.

What do you think?

1.
![1](https://user-images.githubusercontent.com/7602174/59712058-ca0d0c80-91e2-11e9-865e-65c3b39298e0.png)

2.
![2](https://user-images.githubusercontent.com/7602174/59712060-caa5a300-91e2-11e9-92c8-342687cada47.png)

**Comment by holantonela** [comment]
https://marvelapp.com/1gf8bh56/screen/58973568/handoff

**Comment by hellais** [comment]
We agree to drop the carousel and align it to the mock making it 3 column width.
