### ISSUE TITLE
Component filenames should be CamelCase

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#201]
We have some mixed file naming style. We have agreed with @sarathms that we will adapt them to follow CamelCase.

Example:

`MyComponent.js`
```
const MyComponent = () => (<div />)
export default MyComponent
```

**Comment by oliviakeene** [comment]
Hi, I can handle this if no one is currently working on it.

**Comment by sarathms** [comment]
Thank you @oliviakeene. You are welcome to work on this. As a heads up, we are working towards launching this portal later this month. There might be delays in responding to PRs until then. Feel free to ask questions.

**Comment by oliviakeene** [comment]
I'm just wondering if this issue includes the flag file names, and if so what is the naming convention?  Should the file ad.js be AD.js, FlagAD.js, or something else?  Thanks!

**Comment by lucaspontoexe** [comment]
Can I work on it?
