### ISSUE TITLE
Add more meta tags to page headers

### ISSUE THREAD

**Issue by sarathms** [ooni/explorer#202]
Currently, search engines indexing our pages are not able to extract useful information to show search result summaries (as show in screenshot below). By adding `<meta>` tags with relevant properties like `description`, `twitter:image`, `twitter:summary`, `og:*` etc., we can improve these results. Also helps when these pages are shared on social media.

![image](https://user-images.githubusercontent.com/700829/59868158-29435c00-935e-11e9-937b-7640548a4f8b.png)

**Comment by hellais** [comment]
This is done.
