### ISSUE TITLE
Multiple values on y-axis for smaller ranges

### ISSUE THREAD

**Issue by sarathms** [ooni/explorer#204]
When number of measured networks is within a small range of say `[0, 4]`, the y-axis tick values end up as duplicates since we round them off to the nearest whole number.
![image](https://user-images.githubusercontent.com/700829/60038002-19d75200-9681-11e9-972b-78183d7e7a22.png)

This can be eliminated by rounding to one decimal point, but it wouldn't make much sense on the graph. Since we are talking about number of measurements.

**Comment by hellais** [comment]
I am going to look into fixing this.

**Comment by hellais** [comment]
I opened a PR with a fix for this in: https://github.com/ooni/explorer/pull/216.
