### ISSUE TITLE
Globe animation on the home page crashes page

### ISSUE THREAD

**Issue by sarathms** [ooni/explorer#21]
In a production deployment, the globe animation on the home page crashes the pages. First step is to reproduce it in the DEV environment where it doesn't occur right now.

The relevant browser console messages are:
```
TypeError: "this is undefined"
    in e
    in e
    in div
    in Box
    in div
    in Box
    in Flex
    in div
    in Box
    in Container
    in div
    in pages__HeroUnit
    in div
    in div
    in div
    in Root
    in t
    in Rebass.Provider
    in t
    in e
    in t
    in App
```

**Comment by sarathms** [comment]
The feature has now been disabled in the home page for now to prevent the page crash on the test instance.

**Comment by hellais** [comment]
I believe we have completely deleted the globe code from the repo. We can close this issue.
