### ISSUE TITLE
Add zero state for when data is missing

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#215]
A good example of this is: https://explorer-beta.ooni.io/country/IO.

**Comment by hellais** [comment]
cc @holantonela

**Comment by hellais** [comment]
My suggestion is that when we have no data to display we don't display the charts and just display "No data available".

Here is a quick mockup for it:

![NoDataAvailableMockup](https://user-images.githubusercontent.com/424620/62796510-bfcc0800-bad9-11e9-8fd8-2aae600bdf30.png)

The color for the text should be `gray6` and the font size should be 20px for the chart label and the once under websites and networks, while it should be 14px for the one in the Apps section (or whatever the size of the network count text is)

**Comment by holantonela** [comment]
This is good! What is the main action for landers here? Do we want to invite users to run OONI Probe? In that case, we can include a notification at the top saying something close to "OONI works with volunteers for collecting open data, do you want to try? Download OONI Probe"

I know that zero states for countries is not that common. But, we can include this "call for action" banners in countries where we want/need more data.

Do we have a notification component?

**Comment by hellais** [comment]
Yes that is a great idea.

We don't currently have a notification component or anything of this sort. If you have some time to make a mock of it that would be great.

In any case this is perhaps not needed for the launch.

**Comment by holantonela** [comment]
> In any case this is perhaps not needed for the launch.

Agreed. So, let's move forward with "No Data Available" placeholder for this release.
