### ISSUE TITLE
Inconsistency in anomaly indicator on search page 

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#218]
![Screenshot 2019-07-19 at 10 59 08](https://user-images.githubusercontent.com/424620/61523274-4bd79c00-aa14-11e9-9fda-ac8f88cea714.png)

In the search page the legend says "Anomaly" for the orange colored indicator, yet in the pill in the row we say "Likely blocked".

I think "Likely blocked" is too strong of a wording and I would suggest that we align them to both say "Anomaly".

@agrabeli @holantonela what do you think?

**Comment by hellais** [comment]
I think that since we are going to be dropping the legend from the top this is not really an issue anymore.

I am still of the opinion we should use the "Anomaly" label in place of "Likely blocked", but I will leave this decision to @agrabeli .

**Comment by hellais** [comment]
Ah actually an inconsistency still exists in that the filter on the sidebar says Anomalies.

I think the easiest solution is to just align these to what is in the sidebar and use the terminology of "Anomaly" and "Confirmed".

**Comment by agrabeli** [comment]
@hellais I agree that for consistency (and to reduce any potential ambiguity) it's probably best to use "Anomaly" instead of "Likely blocked" for the relevant Web Connectivity measurements. Though I think we should use "Confirmed blocked", as plain "Confirmed" is probably too ambiguous.

**Comment by sarathms** [comment]
Copy has been updated to reflect this.

**Comment by holantonela** [comment]
This looks great and seems fixed. I'm closing this ticket.
