### ISSUE TITLE
Replace Measurement ID with Report ID in measurement page

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#219]
![Screenshot 2019-07-19 at 11 27 34](https://user-images.githubusercontent.com/424620/61525254-4bd99b00-aa18-11e9-86a4-47ddf27d13f7.png)

In the measurement page we are calling Measurement ID what is actually the Report ID.

**Comment by sarathms** [comment]
This is from the copy. I have edited the spreadsheet. This should reflect in the next round of localization update.

**Comment by hellais** [comment]
This is fixed.
