### ISSUE TITLE
Document steps to synchronize localization strings

### ISSUE THREAD

**Issue by sarathms** [ooni/explorer#222]
_Originally posted by @sarathms in https://github.com/ooni/explorer/pull/196#issuecomment-502103621_

As of this PR, the workflow is:

1. `yarn build`
2. `node scripts/extract-react-intl-keys.js` -> ./static/lang/keys.json
3. Download spreadsheet as csv
4. `~/ooni/translations $  ./explorer-sync-csv-source.sh` -> explorer/en/strings.json
5. `python json-key-check.py --json-strings explorer/en/strings.json --json-code ../explorer/static/lang/keys.json`
6. Finally, to build the translations: `cp ../translations/explorer/en/strings.json static/lang/en.json && yarn run build-translations`

**Comment by hellais** [comment]
We may want to look into something similar for probe-desktop as well.

**Comment by majakomel** [comment]
It has been documented here https://github.com/ooni/explorer/pull/748
