### ISSUE TITLE
Questions to answer: Country pages

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#24]
This ticket lists some of the core questions that I think are worth answering (with OONI data) in the new OONI Explorer country pages. 

The main question to be addressed at the start of the page is: **What can OONI data tell me about censorship in X country? What are some of the censorship highlights?**

More detailed/test-based questions below:

# Websites

1. Which websites are blocked (and how)?

2. What types (categories) of websites are blocked? Which types of websites are blocked the most?

3. Is XXX website blocked? When did it first get blocked / since when has it been blocked? Or when did it get unblocked?

4. How does website censorship differ across ISPs? Which ISPs block XXX websites?

**Note:** I acknowledge that question 2 above is rather tricky, since the results will be biased (primarily) depending on (a) which types of URLs are included in test lists and (b) which URLs have been tested, when, & how frequently.

# IM 

1. Which IM apps (WhatsApp, Facebook Messenger, Telegram) are blocked? 

2. Which ISPs block these apps? How does censorship vary across ISPs?

3. How are these apps blocked? Are they blocked with the same censorship techniques?

4. When did the blocking start / when did the blocking stop?

# Circumvention tools

1. Is access to the Tor network blocked (and if so, how)? 

2. How does Tor network blocking vary across ASNs? Which ISPs block Tor and which ones don't?

3. Do Tor bridges work? If so, which ones?

4. In which networks do Tor bridges work? Do Tor bridges work in networks where Tor is blocked?

**Note:** Similar questions would apply to other circumvention tools too (once tests for them have been added). 

# Middleboxes

1. Have middleboxes been detected in any networks? If so, in which networks?

2. Are these middleboxes fingerprintable? Can we identify the vendor(s) of these middleboxes?

3. In which networks do we see signs of network tampering (even if middleboxes aren't identified)?

4. How does network tampering vary across ASNs and over time?

# Speed and performance

1. What is the average speed and performance of XXX network over time?

2. Does NDT data suggest potential throttling in XXX network? Is there a visible drop in the average speed from XXX network (in comparison with other measurements)?

3. Does DASH data suggest potential throttling of video streaming services in XXX network? Is there a visible drop from this network (in comparison with other measurements)?

# Measurement stats

1. How many measurements have been collected from country X over the last month?

2. How many measurements have been collected from country X overall (since the first test was ever run in this country)?

3. How does the volume of collected measurements from country X (over the last month & overall) compare with measurements collected from the rest of the world (other countries in the region & other countries globally)?

4. How many measurements have been collected per test (over the last month & overall) and how do they compare?

5. How many times has each URL been measured (in a time-frame that the user can select) in X ASNs?

6. From which ASNs have measurements been collected (over the last month & overall)? How does the volume of collected measurements differ across ASNs?

7. How does the volume of measurements per test compare across ASNs?

8. How does the amount of ASNs in country X compare with the coverage in terms of measurement collection? (e.g. If country X has 100 ASNs, measurements have been collected from 85 ASNs)

# Contextual country info

* Network landscape

* Internet penetration

* Relevant laws & regulations

* Reported cases of internet censorship

For more info, see: https://github.com/ooni/explorer/issues/1

The above information is not based on OONI data, but we'll engage partners and other community members with manual editing (and we'll pull some information from our research reports). 

From a design/UX perspective, I think it's a question of drawing a balance between (a) making it easy to find this information (i.e. not burying it) and (b) not making this information be the main thing that appears at the top of the page (since for many countries, we may not have information for this section in the beginning).

**Comment by agrabeli** [comment]
Here are some of the core questions that I ask when digging through OONI data on OONI Explorer to write research reports: https://github.com/ooni/pipeline/issues/61

**Comment by elioqoshi** [comment]
Thanks @agrabeli !

i started drafting out a few views to help start a conversation around how these will end up looking.

Regarding Websites: when you say `Which websites are blocked (and how)?` do you also include Anomaly results or only Confirmed Blocked results? I suppose the former?

**Comment by agrabeli** [comment]
@elioqoshi Yes, the former (also including anomalous results, in addition to confirmed blocked).

**Comment by elioqoshi** [comment]
Closing this as the mockups are finished and implementation is in progress.
