### ISSUE TITLE
Handle non-HTML HTTP responses when rendering Web Connectivity measurement

### ISSUE THREAD

**Issue by sarathms** [ooni/explorer#25]
`HttpResponseBodyContainer` throws an exception when it encounters non-string content. e.g for [this measurement](https://explorer.ooni.torproject.org/measurement?report_id=20170917T224102Z_AS12880_Omlea7iGgbh92Y4JoDZAIapJjh3jyXfbDuSfJVtvT5kDdQckVo&input=http://www.runescape.com), the response is an object with `{ data: <encoded string>, format: 'base64'}`

**Comment by hellais** [comment]
I added a fix for this in: https://github.com/ooni/explorer/commit/c7980c936f80fc94de8adf8ef4feb3b193bd2ff6
