### ISSUE TITLE
Country page: websites and apps bar charts should match style

### ISSUE THREAD

**Issue by holantonela** [ooni/explorer#253]
Websites and Apps section in the country pages have bar charts that shows the qty of measurements done in that respective area. We talked about to unify the style of those.

<img width="1364" alt="Captura de Pantalla 2019-08-13 a la(s) 2 17 48 p  m" src="https://user-images.githubusercontent.com/7602174/62963013-809dff80-bdd6-11e9-84c9-498ab747376f.png">

<img width="1353" alt="Captura de Pantalla 2019-08-13 a la(s) 2 17 53 p  m" src="https://user-images.githubusercontent.com/7602174/62962659-b989a480-bdd5-11e9-9275-8637e846a3b9.png">

@hellais what do you think?

**Comment by hellais** [comment]
Yes I think it makes sense to consolidate the style of the charts to be the same.

I personally find the style of the IM apps to be more clear.

**Comment by holantonela** [comment]
> I personally find the style of the IM apps to be more clear.

Me too. Let's use IM apps charts so. Thanks!
