### ISSUE TITLE
The apps charts should be dark grey

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#257]
We currently don't detect anomalies for the IM tests so we should not be displaying those charts in green.

Rather we should change them to be gray8 `#343a40`.

This should be done prior to launch.

cc @holantonela

**Comment by holantonela** [comment]
Thanks for opening this ticket @hellais. It can be done together with #253.

**Comment by hellais** [comment]
>  It can be done together with #253.

I think this is significantly easier than 253 (I expect it to be a one-line fix) and it should be completed prior to launch.
