### ISSUE TITLE
Some links to measurements in websites section of country page don't work

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#259]
I was on the Iran country page and I scrolled down to the Websites section. I tried to open the link "Explore more measurements" displayed under the tested URL, but (a) it took a long time to load the page, even though I'm on a fast network, (b) when it eventually did load, it presented the following error page:

![error-page](https://user-images.githubusercontent.com/8290574/63175159-bb589f80-c043-11e9-8535-4024294cd3b6.png)

The links that took long to load and which presented error pages are the following:

https://explorer-beta.ooni.io/search?test_name=web_connectivity&probe_cc=IR&probe_asn=31549&input=http://www.linkedin.com/&since=2019-07-17&until=2019-08-16

https://explorer-beta.ooni.io/search?test_name=web_connectivity&probe_cc=IR&probe_asn=31549&input=http://twitter.com/&since=2019-07-17&until=2019-08-16

**Comment by sarathms** [comment]
These seem to be working now. @agrabeli can you also confirm this?

**Comment by hellais** [comment]
Yes these search queries work now. Closing.
