### ISSUE TITLE
Add "Explore more measurements" for Circumvention Tools and Networks

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#260]
Currently the Websites and IM results displayed in the country pages of the new OONI Explorer allow users to dig into the measurements by providing the "Explore more measurements" links (which point to relevant measurements in the Search page).

It would be great if similar "Explore more measurements" links were also added for the results under the Circumvention Tools and Network sections, so that users can view measurements pertaining to the displayed results.

**Comment by hellais** [comment]
We have discussed this during this sprint and concluded that more research is needed in order to know what to present. We have documented that as a new issue in here: https://github.com/ooni/ooni.org/issues/386.
