### ISSUE TITLE
Do not show 'No Data Available' while charts are loading

### ISSUE THREAD

**Issue by sarathms** [ooni/explorer#264]
> You should also see if it's easy to ensure that while the chart is still loading you don't say "No data available". I noticed that some of the charts in the lower part of the page say "No data avialable" at the beginning of the load, which may not always be as fast.
> 
> I think it's also fine if it's too much work to document this as an issue and defer to future work.
> 

_Originally posted by @hellais in https://github.com/ooni/explorer/pull/254#issuecomment-522550275_

**Comment by hellais** [comment]
I tried reproducing this, but was unable to.

Closing.
