### ISSUE TITLE
Move overview paragraph to top header of Country pages

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#270]
Based on UX feedback collected at CCCamp, it was proposed that we move the overview paragraph in the Country pages to the top header, right under the Overview heading.

**Comment by hellais** [comment]
You mean the overview summary?
![Screenshot 2019-08-29 at 12 16 14](https://user-images.githubusercontent.com/424620/63932131-dde0b480-ca56-11e9-9ede-cb77530b34e9.png)

I think it's a good idea to move it up and also perhaps improve a bit the copy by making it shorter and highlight the bits of text which are variable (the dates, the measurement counts, etc.).

This is also related to: https://github.com/ooni/explorer/issues/271

**Comment by agrabeli** [comment]
@hellais yep. I just edited the overview paragraph to make it more concise (per feedback). This ticket proposes to move this paragraph to the top of the page.
