### ISSUE TITLE
Edit copy of Overview paragraph to trim it down

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#271]
Based on UX feedback, it was proposed that the copy of the Overview paragraph is made more concise. Perhaps consider replacing the paragraph with bullet points, or with a single sentence, or widgets.

For example:

Since XXX OONI Probe users have collected YYY measurements from ZZZ local networks.

Explore the data below to check the accessibility and/or blocking of sites and services.

**Comment by hellais** [comment]
Yes I think this is a good idea.

**Comment by agrabeli** [comment]
@sarathms I have edited the copy of the Overview paragraph in the relevant string (per these suggestions). Please update the deployment.
