### ISSUE TITLE
Replace "input" with "Domain" in Search page

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#274]
Edit the copy to replace "Input" with "Domain" in the Search page so it's clear to users what we mean.

**Comment by hellais** [comment]
This is related to: https://github.com/ooni/api/issues/52

**Comment by hellais** [comment]
I suspect we will not be able to complete this by the time of the launch as it also requires backend and pipeline related changes.

**Comment by hellais** [comment]
It turns out it's possible to do this only in the API and we already win a bunch of performance, so I went ahead and did it.

@sarathms in order to update the code you should use the  `domain=` query parameter instead of the `input=`

**Comment by agrabeli** [comment]
I think (in response to this ticket) @hellais edited the Search.Sidebar.Input string (in the spreadsheet with the copy) to Search.Sidebar.Domain, but this is not reflected in the beta deployment:

![domain-search](https://user-images.githubusercontent.com/8290574/64127696-14019980-cdb3-11e9-942e-8a12d528e52c.png)

@sarathms please make necessary changes so that the new OONI Explorer says "Domain" (per changes in the spreadsheet). Thanks. :)
