### ISSUE TITLE
Swap the order of Test Name & Country drop-down menus in Search page

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#275]
Community members proposed that we swap the order of the Test Name & Country drop-down menus in the Search page so that the Country drop-down menu is presented first.

This would be an important thing to do, particularly since most users probably won't recognize OONI Probe test names.

**Comment by hellais** [comment]
Yes I think we should put it right above the test name selector so that they go together.

**Comment by sarathms** [comment]
Further, I would propose that we move dynamic fields like input/domain and status radios to the bottom of the sidebar. These would appear or hide themselves depending on the test name. Here's what it would look like.
![image](https://user-images.githubusercontent.com/700829/63950122-6e17fd00-ca49-11e9-9fb2-2d41e4ea92d3.png)

@hellais @agrabeli Do we see any UX problems with this?

**Comment by agrabeli** [comment]
@sarathms I think that's a great suggestion! That makes a lot of sense, particularly since Input is only relevant to the Web Connectivity test.
