### ISSUE TITLE
Fix UI 'jump' in transition from content loader to charts in Websites section

### ISSUE THREAD

**Issue by sarathms** [ooni/explorer#278]
As we start loading charts in the website section, the two stage transition from `WebsiteSectionLoader` to a bunch of `WebsiteChartLoader`s to the actual charts, the section appears to jump a pixels vertically. This is mostly due to a mismatch is the rendered dimensions of the content loaders and the actual content (chart boxes).

Previous discussion and attempts to fix this was done here: https://github.com/ooni/explorer/pull/263#discussion_r319165924

**Comment by hellais** [comment]
Is this still an issue or has it been fixed?

**Comment by hellais** [comment]
I tried reproducing this and I cannot. Closing this as invalid.
