### ISSUE TITLE
Filter Web Connectivity measurements based on categories

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#288]
Currently you can only filter measurements based on parameters like ASN (which is great!), date range, test name, etc.

It would be *fantastic* is we could filter Web Connectivity measurements based on *categories*. :)

I am referring to the Citizen Lab categories used in test lists: https://github.com/citizenlab/test-lists/blob/master/lists/00-LEGEND-new_category_codes.csv

**Comment by hellais** [comment]
This is related to: https://github.com/ooni/explorer/issues/246

**Comment by hellais** [comment]
This also requires some pipeline related changes in order to ingest the category codes for URLs and support filtering for it.
cc @FedericoCeratto 

It's a pretty large feature. I will make this an epic.

**Comment by hellais** [comment]
We now have support for doing this in the backend. We still have to expose this inside of the API.

**Comment by hellais** [comment]
We have support for this in the API, so it's just a matter of adding UI support for it.

**Comment by agrabeli** [comment]
@sarathms it would be great to add support for filtering based on website categories in the OONI Explorer Search tool. Then those pre-filtered measurements can be accessed through the MAT, when the user filters based on category codes.

**Comment by FedericoCeratto** [comment]
Small bugfix deployed. API call example: https://api.ooni.io/api/v1/measurements?category_code=NEWS
