### ISSUE TITLE
Query doesn't work

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#296]
This query doesn't seem to work (as it's loading indefinitely): http://explorer-beta.ooni.io/search?until=2019-09-11&domain=www.privateinternetaccess.com&probe_cc=HK

^^ @hellais

**Comment by agrabeli** [comment]
Actually never mind, it now says "No results found" (presumably because the URL in question hasn't been tested in HK yet). There seems to be a bit of a performance issue in that it took long to render this result, in comparison to the old Explorer. I guess we could potentially close this ticket.

**Comment by sarathms** [comment]
Let's close it until we see it happening again after the current backend optimization efforts are done.
