### ISSUE TITLE
 Error after receive timeout error (json) from API: "There was an unexpected error from our end."

### ISSUE THREAD

**Issue by xhdix** [ooni/explorer#321]
## Expected Behavior
Show timeout error message

## Actual Behavior
Page crashed and displays an error:
```
There was an unexpected error from our end.
Maybe try exploring some measurements or go to our homepage.
```

## Steps to Reproduce the Problem

  1.  open: https://explorer.ooni.org/search?until=2019-09-18&domain=anidalton.blogfa.com&only=confirmed

## API response 
```json
{
  "detail": [
    "The database query timed out.",
    "Try changing the query parameters."
  ],
  "status": 504,
  "title": "Gateway Timeout",
  "type": "about:blank"
}
```

**Comment by sarathms** [comment]
You are right. The error page should be a bit more transparent.

**Comment by xhdix** [comment]
What complicates the situation is the need to (1) return back and (2) refresh the page and (3) set the values again.

**Comment by hellais** [comment]
Yes this sounds like something we want to do. I suggest we include as part of the error message also the full JSON response from the API server.

My suggestion is to check for the `detail` key, if it's present you should concatenate that array and add it as a `<p>` below the "There was an unexpected error from our end." string and then include below also inside of `<pre>` or code block styled element the full JSON of the API response as well.
