### ISSUE TITLE
Add matomo analytics code

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#326]
Similarly to how we track stats on our main website we should do it for OONI Explorer too.

It's a matter of adding to every page the following snippet:

```
<!-- Matomo -->
<script type="text/javascript">
  var _paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//matomo.ooni.org/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '2']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->
```

The tracking code is configured to not store the full IPs of visits and respect do-not-track policies etc.

**Comment by BhaveshSGupta** [comment]
I would like to try this one.

**Comment by sarathms** [comment]
@BhaveshSGupta you are welcome to take this up.

I did a quick search and found [this package](https://github.com/Amsterdam/matomo-tracker/tree/master/packages/react) which provides a hook that can be useful to understand usage of specific parts of the site. It would be great if you can use it. Feel free to propose alternatives.
