### ISSUE TITLE
Link to measurements on OONI Explorer Country pages

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#338]
The OONI Explorer country pages provide aggregate information (which is great!), but they no longer share the bulk of all individual measurements collected from that country. The old OONI Explorer used to do that, which is why I used to reference OONI Explorer country pages in research reports. Now, if I reference an OONI Explorer country page, it doesn't share the measurements collected from that country in an easy-to-find way (only some links are included that point to measurements for specific tested resources). 

I therefore propose that we add a button (or something that makes it obvious and easy to find) at the start of each OONI Explorer country page which links to the Search page for that country, enabling users to easily/quickly gain access to all measurements collected from that country.

For example, the Egypt page (https://explorer.ooni.org/country/EG) would have a link (that is easy to find) to: https://explorer.ooni.org/search?until=2019-10-26&probe_cc=EG

**Comment by hellais** [comment]
An easy thing we can do is make the description in the first block clickable see the following mock:
![Measurements link.png](https://images.zenhubusercontent.com/58442543b9dc3c622022e97d/21847bc2-2acd-453d-863b-91101c385e56)

@sarathms @agrabeli what do you think?

**Comment by agrabeli** [comment]
@hellais I think that's a great idea!

**Comment by sarathms** [comment]
I tried this out to see if it as obvious as I thought it is. And it is.
![image](https://user-images.githubusercontent.com/700829/99432199-cf8bec00-28d9-11eb-9239-49524dcfd29d.png)

Noting down the change here for my own reference:
```
measurementCount: `<a href='/search?probe_cc=BJ'>${intl.formatNumber(measurementCount)}</a>`,
```

**Comment by hellais** [comment]
@sarathms can you link also the `measurements` word?

**Comment by hellais** [comment]
The UX work is done. Re-assigning @sarathms to the issue.

**Comment by sarathms** [comment]
> can you link also the measurements word?

I _think_, yes. They have to be linked separately to the same URL.
