### ISSUE TITLE
Measurement Pages design improvements and fixes

### ISSUE THREAD

**Issue by elioqoshi** [ooni/explorer#35]
Related to issue https://github.com/ooni/explorer/issues/11

We are collecting feedback here to do another iteration with fixes and design tweaks for the meaurement pages implemenation.

First review can be found here: 
https://github.com/ooni/explorer/issues/11#issuecomment-449023602

**Comment by elioqoshi** [comment]
@sarathms quick feedback from my end:

- First off, in the mockups we have a wider body width, whereas in the implementation it's very narrow. Could you refer to the mockups layout width for that?

- Related to the first point, many font sizes are off as well: The header values are currently 24px but should be 28px. The headings in `Other Details` or `Raw Measurement Data` are also 22px but should be 24px. Also the value font size in the "Other Details" section is 16px but should be 18px. Same gooes to the description above which overflows which should be 28px and not 16px.

- The tick icon for `Reachable` is not the one we use. Let me know if you have trouble getting that icon.

- The test class and test name are in black, while the test class should be in white, with the container in the test class color and the test name in the same color.

- Below that, the text seems to be overflowing. This also happens in the Raw Measurement Data field. The data should have its own scrollbar instead of changing the whole webpage's width. Here is the screenshot of the whole page how it looks on my latest Firefox:

![image](https://user-images.githubusercontent.com/5436686/50291445-e5cf6a00-046e-11e9-92e8-9de7a8f2a53e.png)

- The `DOWNLOAD JSON` button should be in Title Case instead, so `Download JSON`. Also it's currently 11px while in the mockups it's 20px. 

- In the `Other Details` field could you give some more space between the rows/ raise the line height? Also the padding to the top of the box background should be reduced a little bit (refer to mockups)

---

All over there are many things which can be answered by the mockups if you use their values as a reference. Happy to jump on a 1:1 as well to go through these. Thanks for the quick progress so far!

**Comment by elioqoshi** [comment]
I agree with doing changes in the design system as that is also making things easier to track later on. Ideally, everything (web at least) should be using a source from the design system and exceptions should be minimal.

Regarding the maxWidth:
960 is considered to be the standard for an optimal reading experience. This however is no blog but rather a web application with various columns, so restricting it to half of the screen width for most users is restrictive I'd say. Some more reading related to this: https://ux.stackexchange.com/questions/104745/whats-the-recommended-max-width-for-the-main-container-and-for-the-main-column

Having said that, we would ideally adapt the design system to support a wider width (something like 1280 or 1366) for this reason but we should keep in mind that this might not be an ideal solution for the maxwidth for e.g the OONI Blog in the future website. Would it be possible to have an alternative layout for this case?

Same goes for the font size. When we set the initial font sizes it was based on research, while during the design of the Explorer pages, I have a better understanding of the text hierarchy and generally have a better feel of it. The following are what I'd suggest and which are fully compatible with the Explorer mockups as well: 
![image](https://user-images.githubusercontent.com/5436686/50688678-ca479000-1026-11e9-801e-9095eaf3608e.png)

I based some of them on the Material Design system but would like to have your feedback regarding adapting the design system to this.
Some notes:
- H1 and H2 will rarely be used, but they have their uses, so it's good to keep them reserved for some cases. 
- 16px body does not work in some part of the interfaces where 14px is needed, hence Body 1 and Body 2. 

> I am not sure a scrollbar is the right solution to this problem. Scrollbars are annoying and in this particular case (since it's not really useful for the user to read the text), they don't help that much.

> I would say it's probably wiser to just truncate stuff that is wider than the view with something like overflow: hidden.

I have my doubts whether all cases are of no use to the user. Can't we wrap the text (or soft wrap)?

> This is another thing where we need to make up our mind on. For example run.ooni.io uses CAPS CASE. Do we want to change this in the design system and always use Title case for it?

Yeah, we decided to turn the buttons into Title Case some time ago for readability reasons. I'd suggest have a set of buttons in any case for when we don't have enough screen estate for button margins:

Primary, Secondary and Outlined in Default, with Icon and Compact variations:
![image](https://user-images.githubusercontent.com/5436686/50688981-29f26b00-1028-11e9-818b-e6857fafbfbd.png)

As of now we use Primary Buttons everywhere which might not be ideal if there are multiple Call to Actions.

--

Generally I'm going through the whole design system and proposing some updates to unify it as much as possible, while doing minimal changes to the current work (unless it saves us work in the future).

**Comment by hellais** [comment]
@elioqoshi @holantonela this is ready for review from the perspective of a beta. It is deployed here: https://ooni-explorer-next.test.ooni.io

**Comment by hellais** [comment]
@elioqoshi @holantonela can you take a look at it and if it's good close this ticket?

**Comment by holantonela** [comment]
@hellais could you link one working link for each measurement status? Thanks!

**Comment by hellais** [comment]
> could you link one working link for each measurement status? Thanks!

@holantonela you can find a list of them here: https://github.com/ooni/explorer/issues/11#issuecomment-449262759

**Comment by elioqoshi** [comment]
@sarathms the measurement pages are still quite far from the mockups and we need to do these changes so we can get these up to speed. Please also refer to my first comment https://github.com/ooni/explorer/issues/11#issuecomment-449023602

Taking this page as an example:

http://ooni-explorer-next.test.ooni.io/measurement?report_id=20190326T163342Z_AS267164_tDXK6sBlPjHmi220kZRKZhY6fRBgqsLT6unDEfbfPdj9Q55i7T&input=http://traipu.al.gov.br/

Failures
DNS Queries
TCP Connections

are not place ideally and arranged in columns of 2 on the page. All elements should be in a single column like in the mockups and everyone of these boxes should be within a container, just like the meta data box below

- A major shortcoming not addressed yet is the lack of collapse/expand buttons for the raw data / json / etc. I'd suggest the raw data to be collapsed by default though. Please ensure that any code / raw data view like this should look the same (it currently does not when you look at HTTP Request and Raw Data for example).

- Raw Data is still not wrapped and overflows the page width. This width should be inside the code container, not the whole page width (hope that makes sense).

As said, I'd be happy to jump on a live session with you to fix these issues in real time if you prefer.

**Comment by hellais** [comment]
@holantonela do you think we can close this now?

**Comment by holantonela** [comment]
I checked the urls listed in https://github.com/ooni/explorer/issues/11#issuecomment-449262759
This seems done. Great work @sarathms and @elioqoshi !
