### ISSUE TITLE
Explorer should publish measurements from the fastpath

### ISSUE THREAD

**Issue by anadahz** [ooni/explorer#352]
## Expected Behavior

RSS feed URLs should link to the correct URLs.

## Actual Behavior

Wrong explorer URLs in RSS feeds

## Steps to Reproduce the Problem

  1. Visit any link from the RSS feed: https://explorer.ooni.org/rss/global.xml

**Comment by hellais** [comment]
You are likely seeing those links not working because they are for measurements that are inside of the fastpath and those are not yet deployed on the public API, hence not available in explorer.

Here is the issue for that: https://github.com/ooni/sysadmin/issues/394

**Comment by hellais** [comment]
This is now done. Closing.
