### ISSUE TITLE
Ability to search for IP

### ISSUE THREAD

**Issue by xhdix** [ooni/explorer#354]
These four URLs cannot be searched in explorer:
https://github.com/citizenlab/test-lists/blob/master/lists/global.csv#L1148-L1151

The problem is from the frontend.
http://explorer.ooni.org/search?until=2019-12-04&domain=1.1.1.1&test_name=web_connectivity&since=2019-11-01

## Expected Behavior
Ability to search for IP

## Actual Behavior
error: `Please enter a valid domain name, such as twitter.com`

## Steps to Reproduce the Problem

  1. write: 1.1.1.1

**Comment by SaptakS** [comment]
I would like to work on this issue if no one else is working on it.
