### ISSUE TITLE
Conflirmed filter doesn't work

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#355]
We were notified by community members that the Confirmed filter on OONI Explorer doesn't work.

The example they showed was based on filtering for Iraq and Confirmed, which only showed the most recent measurements (from all tests), irrespective of testing status.

I just checked and can confirm that this query doesn't work: http://explorer.ooni.org/search?until=2019-12-06&probe_cc=IQ&only=confirmed

It doesn't work for any other country either. For example: http://explorer.ooni.org/search?until=2019-12-06&probe_cc=IR&only=confirmed

When selecting Web Connectivity, it doesn't seem to work either: http://explorer.ooni.org/search?until=2019-12-06&probe_cc=IR&only=confirmed&test_name=web_connectivity

Perhaps this filter has been disabled?

**Comment by xhdix** [comment]
And the result of all measurements is `accessible`. (in search page)

**Comment by hellais** [comment]
A fix for this has been implemented and shipped.

See: https://github.com/ooni/api/pull/140
