### ISSUE TITLE
Fail to display the measurements with IP address

### ISSUE THREAD

**Issue by xhdix** [ooni/explorer#356]
When the `input` parameter value is IP, the `Status Code: 500 Internal Server Error` occurs.

failed: 
http://explorer.ooni.org/measurement/20191205T221330Z_AS12880_EQMMhHqRhRQ9zpM74QCIh055mmnPOGRVsqaRM5JjcJPkXLipBr?input=https://9.9.9.9/dns-query?dns=q80BAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB

http://explorer.ooni.org/measurement/20191205T221537Z_AS44244_NbZ6i06wRO6OQorMyagz5XRybCMQfQNNqaVeQvsHlTp0VG9LoY?input=https://1.1.1.1/dns-query?dns=q80BAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB

http://explorer.ooni.org/measurement/20191205T221330Z_AS12880_EQMMhHqRhRQ9zpM74QCIh055mmnPOGRVsqaRM5JjcJPkXLipBr?input=https://1.1.1.1/dns-query?dns=q80BAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB

without problems:
http://explorer.ooni.org/measurement/20191205T221537Z_AS44244_NbZ6i06wRO6OQorMyagz5XRybCMQfQNNqaVeQvsHlTp0VG9LoY?input=https://dns.quad9.net/dns-query?dns=q80BAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB

http://explorer.ooni.org/measurement/20191205T221330Z_AS12880_EQMMhHqRhRQ9zpM74QCIh055mmnPOGRVsqaRM5JjcJPkXLipBr?input=https://cloudflare-dns.com/dns-query?dns=q80BAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB

**Comment by SaptakS** [comment]
This issue should be fixed by [the following PR](https://github.com/ooni/explorer/pull/363). The master branch seems to be working fine with the above paths and params. I am guessing the PR has not yet been deployed and hence in prod website it's still giving error.

**Comment by xhdix** [comment]
@SaptakS We have to wait until the next release. :P

**Comment by SaptakS** [comment]
@xhdix no problem. I definitely understand. :)

**Comment by hellais** [comment]
This is deployed. Closing!
