### ISSUE TITLE
‘confirmed blocking’ measurements

### ISSUE THREAD

**Issue by gabelula** [ooni/explorer#36]
Currently it's not possible to determine the "confirmed" flag of measurements from the raw measurement.

This flag is only available in the search listing of the API. We should come up with a way of delivering annotations from the pipeline stored in the metadb to the explorer measurement pages.

**Comment by hellais** [comment]
In reality this is easier to do than I expected. An example of how these can be retrieved from the top level measurement page component can be seen in this commit: https://github.com/ooni/explorer/pull/42/commits/b56ffe684f4e239595fb09d5f4f92c4be22a4271.

 I would suggest that for the time being we don't do any pipeline or backend modifications to extract these fields or inject them into measurements, but just use the pattern in the above commit.

**Comment by hellais** [comment]
I am reassigning this to sarathms as this should just be a matter of using those props inside of the components to show the relevant views.
