### ISSUE TITLE
Default value of until filter should include measurements of today

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#361]
Currently the `until` filter is set to default to the current date. The problem with this is that I would expect it to filter inclusive of all measurements for the date of today, but instead it filters measurements until midnight of today (effectively yesterday).

I think we should fix this by making it so the until filter is set by default to the date of tomorrow instead of the date of today.

**Comment by SaptakS** [comment]
I am willing to work on this issue if no one else is working on it.

**Comment by hellais** [comment]
Thanks for that! Nobody is currently working on it and I would say it's an important issue to pickup.
