### ISSUE TITLE
Make sure we use UTC time when showing measurements

### ISSUE THREAD

**Issue by bassosimone** [ooni/explorer#368]
Following up from https://github.com/ooni/explorer/pull/364#pullrequestreview-337165238, we should make sure we're using UTC time when showing measurements. I am not so familiar with the codebase to state that we must always use UTC, but we most likely need UTC in most cases.

(It _may_ be a nice feature to _also_ show the presumed local time when the measurement was taken based on the country, but this strikes me as an entirely different feature.)

**Comment by SaptakS** [comment]
I can work on this issue.
