### ISSUE TITLE
Missing server location element from ndt/DASH test

### ISSUE THREAD

**Issue by gabelula** [ooni/explorer#37]
We need more information about this ticket.

**Comment by hellais** [comment]
Basically this is about including the location of the NDT and DASH server in the measurement pages. For some reason it was at some point dropped from the mocks and we should find a way to re-add it there.

cc @elioqoshi @holantonela

**Comment by holantonela** [comment]
@elioqoshi could you link the iterated version including the location of the NDT and the DASH server here? Thanks!

**Comment by elioqoshi** [comment]
Thanks for bringing this up, will update the mockups accordingly.

**Comment by holantonela** [comment]
We can include the server location information by adding a new item:

![Group](https://user-images.githubusercontent.com/7602174/59622624-7928e580-9108-11e9-9625-e00d592dd871.png)

**Comment by bassosimone** [comment]
The reason why it is so is that DASH does not store the server name but just the IP address. I guess this was enough back in the day when I used it to write papers:

```
                "connect_time": 0.07800412178039551,
                "constant_bitrate": false,
                "delta_sys_time": 0.0,
                "delta_user_time": 0.0,
                "elapsed": 1.987497091293335,
                "elapsed_target": 2,
                "engine_name": "libmeasurement_kit",
                "engine_version": "0.10.4",
                "fast_scale_down": false,
                "internal_address": "192.168.1.2",
                "iteration": 15,
                "platform": "macos",
                "rate": 89586,
                "real_address": "109.116.253.87",
                "received": 22396500,
                "remote_address": "41.231.21.19",
                "request_ticks": 1560864109.246374,
                "timestamp": 1560864109,
                "use_fixed_rates": false,
                "uuid": "d9d3bb00-776c-4d0b-b311-923c254aa9ec",
                "version": "0.007000000"
            }
```

I'm going to also include the server name: https://github.com/measurement-kit/measurement-kit/issues/1865
