### ISSUE TITLE
[React Intl] An `id` must be provided to format a message on measurement page

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#374]
Reported by a user that this page crashes: https://explorer.ooni.org/measurement/20200115T114026Z_AS44244_Iyw2f9XWy5vMHnWZgk3Gaah0oGlswxY8XlR49dvmorgbRZW4n5?input=https://github.com/

I was able to reproduce the bug locally and found the stacktrace to be:
```
[React Intl] An `id` must be provided to format a message.

WebConnectivityDetails
./components/measurement/nettests/WebConnectivity.js:326
  323 |   )
  324 | } else if (isAnomaly) {
  325 |   status = 'anomaly'
> 326 |   reason = intl.formatMessage(messages[`blockingReason.${blocking}`])
      | ^  327 |   summaryText = (
  328 |     <FormattedMessage
  329 |       id='Measurement.SummaryText.Websites.Anomaly'
```

**Comment by sarathms** [comment]
The particular measurement ([raw json](https://api.ooni.io/api/v1/measurement/temp-fid-005eb9ffc3143a8d2b487eb3e44024fa)) in question looks weird. The metadata for the msmt says 
```
{
      "anomaly": true,
      "confirmed": false,
      "failure": false,
      "input": "https://github.com/",
      "measurement_url": "https://api.ooni.io/api/v1/measurement/temp-fid-005eb9ffc3143a8d2b487eb3e44024fa",
      "probe_cc": "IR",
}
````
And in the `test_keys`, where we expect `blocking` to be a truthy value it has
````
  "test_keys": {
    "accessible": true,
    "agent": "redirect",
    "blocking": false,
    "body_length_match": true,
    "control_failure": null,
    "dns_consistency": "consistent",
    "headers_match": true,
    "status_code_match": true,
    "title_match": false
````
Has it something to do with `title_match: false`?

**Comment by hellais** [comment]
I suspect this is due to: https://github.com/ooni/explorer/issues/360.

My suggestion is that we should make the explorer code resilient to this, but I think we should more broadly discuss how we can avoid having too much detection logic inside of Explorer and rather defer to the pipeline as the source of truth on that.

I think @FedericoCeratto also may have some thoughts on this.

**Comment by hellais** [comment]
That is to say that maybe the pipeline should also be responsible for producing the values for `blockingReason` and it should include these inside of the top level metadata listing. @FedericoCeratto what do you think?

**Comment by sarathms** [comment]
> discuss how we can avoid having too much detection logic inside of Explorer

Well, at least in this case, explorer is not doing any detection logic. Even before we fetch the full measurement for the `test_keys` we render measurement pages as `reachable`, `anomaly`, `blocked` or `error` and then just show the relevant details in their designated UI elements.

**Comment by sarathms** [comment]
> discuss how we can avoid having too much detection logic inside of Explorer

Well, at least in this case, explorer is not doing any detection logic. Even before we fetch the full measurement for the `test_keys` we render measurement pages as `reachable`, `anomaly`, `blocked` or `error` and then just show the relevant details in their designated UI elements.
