### ISSUE TITLE
Present Web Connectivity measurements chronologically when filtering by ASN

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#379]
I tried filtering Web Connectivity measurements based on a specific domain and ASN, but the filtered measurements were not presented chronologically. 

For example: https://explorer.ooni.org/search?until=2020-01-23&domain=www.accessnow.org&probe_cc=EG&probe_asn=AS24863

This bug does not occur when filtering purely based on a domain (for example: https://explorer.ooni.org/search?until=2020-01-23&domain=www.accessnow.org&probe_cc=EG).

It would be helpful if measurements are presented chronologically when filtered by domain + ASN. Thanks!

**Comment by hellais** [comment]
This sounds more like an OONI API issue, Explorer does not do any ordering itself.

@FedericoCeratto do you know what may be causing this?

**Comment by hellais** [comment]
This seems to have been resolved. Closing.
