### ISSUE TITLE
Download measurement data in json 

### ISSUE THREAD

**Issue by gabelula** [ooni/explorer#38]
The download measurement button uses Javascript and `datauri` to make the raw measurement be donwloadable. We should instead use `href` pointing to the raw measurement on the OONI API. 

This allows non-js browser to download it, overcomes the datauri filesize limitatio and also makes it easier to share the download link.

**Comment by hellais** [comment]
This is done in: https://github.com/ooni/explorer/commit/263594d0dec96df5e129235a56d1190b68659c91
