### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined with telegram test

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#381]
Happens with this measurement generated from miniooni: http://localhost:3100/measurement/20191004T105200Z_AS30722_V8ZfdAXLEjTfRb37osawgJRS3MZLVh91DYi1TXjVcXFQQmP9Bj

**Comment by sarathms** [comment]
The measurement is missing the `tcp_connect` key in `test_keys`.

**Comment by hellais** [comment]
Can we make this OONI Explorer page handle the missing `tcp_connect` field? Should we also check if there are other places in which we want to make it more robust to this field missing?
