### ISSUE TITLE
Update pattern for showing failing measurements

### ISSUE THREAD

**Issue by gabelula** [ooni/explorer#39]
Example https://ooni-explorer-next.test.ooni.io/measurement?report_id=20181217T181225Z_AS55836_VWJS5HXHsuaQe9S1aygtrQVi2LZUCMKjkt907vcT0RkKdHJLDi

**Comment by sarathms** [comment]
Updated URL: https://explorer-beta.ooni.io/measurement?report_id=20181217T181225Z_AS55836_VWJS5HXHsuaQe9S1aygtrQVi2LZUCMKjkt907vcT0RkKdHJLDi

This seems to be fixed in the recent versions.

**Comment by hellais** [comment]
This is now done.
