### ISSUE TITLE
Blank items are shown on search result list

### ISSUE THREAD

**Issue by ksangchan** [ooni/explorer#400]
<- Remember to label this issue accordly (bug, feature, help wanted, etc). And remove any information that does not fit the issue you are submitting.  -> 

## Expected Behavior
Search result should not contain blank or duplicate items.

## Actual Behavior
For some search result entries, an extra blank item (blank on url column) which links to the same measurement is shown.

## Steps to Reproduce the Problem

  1. Go to https://explorer.ooni.org/search?until=2020-02-12&probe_cc=CN&since=2020-02-05&test_name=web_connectivity
  2. Observe that there are entries near the bottom that has blank url, but actually links to the measurement same as the previous one.
![Screenshot_20200212_165807](https://user-images.githubusercontent.com/52733452/74381268-1e3faf00-4db9-11ea-9ec5-5a47ea41c897.png)

## Specifications

  - Version: Firefox 72
  - Platform: Linux
  - Subsystem:

**Comment by FedericoCeratto** [comment]
Fixed with a manual run of domain_input_updater.

Thanks for the bug report!
