### ISSUE TITLE
Use the isAnomaly and Confirmed from the fastpath or batch pipeline

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#403]
We need to align the colors and anomaly status of the listMeasurements to the measurement pages.

The logic for calculating the screens needs to be minimal and explorer should not make any assumptions about the results, but just render what is presented to it.

If the anomaly == true, but blocking is false, it will say "Unknown" as blocking reason.

This is related to #360 .

**Comment by sarathms** [comment]
This is not what was addressed in #401 right?

**Comment by hellais** [comment]
Correct, this was not addressed in #401, though some additional robustness, similar to that, should be done as part of this work.

Basically we should use the `isAnomaly` and `isConfirmed` value from the pipeline to pick the color and anomaly flag (how we were doing it before), but make the code more robust such that when `blocking: false`, but `isAnomaly == true`, the pages don't break.

We can discuss this 1-1 later if you need more information.

**Comment by hellais** [comment]
This has been implemented for the web_connectivity test. Closing
