### ISSUE TITLE
Fix issues in the WhatsApp measurements page

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#406]
Currently the WhatsApp result page is using the isAnomaly flag coming from the API which is not set for all old measurements.

This means that some measurements which are in fact blocked will be marked as green for measurements which are not in the fastpath.

In practice this means that measurements that are **older** than 2-3 days, may not present accurate results in the measurement page.

This issues is to address this problem and will also be linked from the measurement page for WhatsApp.

**Comment by hellais** [comment]
On Explorer pages affected by this issue we display the following message:

<img width="1350" alt="Screenshot 2020-02-22 at 13 18 50" src="https://user-images.githubusercontent.com/424620/75092368-1630fd80-5577-11ea-8132-6dd41b30acae.png">

**Comment by sarathms** [comment]
It seems this problem doesn't exist anymore. For example, [this measurement from 2019](https://explorer.ooni.org/measurement/20190228T161239Z_AS4837_QwJJklGAXLLvpS92WGeEuab9eaW8TyUBfvyZQfKB0JwhP9xdNB), is correctly presented as an anomaly and comes up in the search results also as an anomaly.

I think we can close this issue. @hellais @FedericoCeratto What do you think?

**Comment by hellais** [comment]
@sarathms let's drop the message saying that it's presenting a known processing issue (and fix the styling of the yellow box around the infoboxes) and close it then:
![Screenshot 2020-12-03 at 11 13 23](https://user-images.githubusercontent.com/424620/100995867-a796bc80-3558-11eb-9ba1-70f2497d47cb.png)

**Comment by hellais** [comment]
@sarathms I am unable to filter by the measurement in the original screenshot. I get this error message:
![Screenshot 2020-12-03 at 11 16 18](https://user-images.githubusercontent.com/424620/100996159-05c39f80-3559-11eb-9e28-c511e65eb825.png)
https://explorer.ooni.org/search?until=2019-11-31&since=2019-11-30&probe_cc=AR&test_name=whatsapp

**Comment by hellais** [comment]
We have removed the box in the page, so we don't have to do anything else for this issue. Closing.
