### ISSUE TITLE
Fix presentation of Tor results on OONI Explorer

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#421]
When I run the new Tor test via the new OONI Probe desktop app, the test result in the app says that Tor works and the result is presented in green.

However, when I open this measurement in OONI Explorer, it doesn't present the result (whether Tor works of not): https://explorer.ooni.org/measurement/20200313T135837Z_AS30722_5HI5roRCR9EXw0tGVd4NBlTNHDqkRNnAXkB75qSHgp0k8D9onV

![tor-test](https://user-images.githubusercontent.com/8290574/76630402-3c2b3b80-6540-11ea-94c5-297837e51e57.png)

We probably need to analyze the Tor test results in the pipeline to present the results in OONI Explorer.

**Comment by sarathms** [comment]
As per @FedericoCeratto, the issue ooni/backend#210, blocking this one, will be addressed after September.

**Comment by sarathms** [comment]
@agrabeli Can you confirm that this issue is now resolved? There are now [Tor measurements shown as anomalies](https://explorer.ooni.org/search?until=2021-03-24&since=2021-02-22&test_name=tor&only=anomalies).

**Comment by hellais** [comment]
Yes this is now fixed.
