### ISSUE TITLE
JSON View Data overflows in search small screen

### ISSUE THREAD

**Issue by NidhiKJha** [ooni/explorer#428]
## Expected Behaviour

The content in the Box should not overflow (JSON data).

## Actual Behaviour

 The data overflows in mobile view

![WhatsApp Image 2020-03-20 at 12 20 04 PM](https://user-images.githubusercontent.com/39872794/77160167-d35a3b00-6acc-11ea-95eb-43599bf3b8c6.jpeg)

## Steps to Reproduce the Problem

  1. Click on `search` on the homepage
  2. Select any country
  3. In Raw, Measurement Data collapse (toggle to view JSON) it in the mobile-view

## Specifications

  - Platform: Mobile-view

**Comment by hellais** [comment]
This has been merged.

Thanks @NidhiKJha!
