### ISSUE TITLE
Make the measurements URL consistent with the current explorer

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#43]
In the current explorer a measurement is found at:

`https://explorer.ooni.io/measurement/$REPORT_ID?input=$URL`

In the revamped explorer the path is:

`https://explorer.ooni.io/measurement?report_id=$REPORT_ID&input=$URL`

Before we deploy OONI Explorer we should be sure that at the very least URL rewriting is in place to either do a 301 redirect or to serve at the same URL the old measurements (so that links don't break and search engines are happy).

Related to this is also the new measurement ID scheme, so eventually the format `report_id=$REPORT_ID&input=$URL` will also be dropped. So I suspect we are better off implementing the new explorer using the legacy scheme and reserve doing a 301 redirect for when we have a msmt_id for every measurements (and maybe the path should then become `explorer.ooni.io/m/$MSMT_ID` to avoid conflicts.

**Comment by sarathms** [comment]
We are now able handle the URLs used by the old explorer correctly. I only completed what was partially implemented in the initial code to handle these URLs. It used to ignore the `?input=url` portion which is now appended processed.

@hellais However, this isn't a 301 redirect. Do we still need to do this to address any search engine requirements?

**Comment by hellais** [comment]
> However, this isn't a 301 redirect. Do we still need to do this to address any search engine requirements?

I don't think we should do a 301 redirect, but I think we should make changes to the links in the search page results and other pages that reference measurements to ensure they are following the old pattern.
Otherwise we will run into the issue of duplicating indexed pages.

**Comment by hellais** [comment]
I have confirmed however that old links from OONI Explorer work well with the new one.

So the only remaining item to compete this is:
* Ensure measurement page links from other pages inside of OONI Explore use the pattern `/measurement/$report_id?input=XXX`
