### ISSUE TITLE
Display type of anomalies in the Search page listing of anomalous Web Connectivity results

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#438]
The great thing about the new Search tool of OONI Explorer is that it enables you to browse through many measurements at once and to have a bird's eye view of results. 

For example, the following page through the Search Tool provides a bird's eye view of potentially blocked websites in Italy across many different networks.

![it-explorer](https://user-images.githubusercontent.com/8290574/77791122-5ef04080-7066-11ea-8eb7-ffaafa2745ea.png)

Unless a block page is served, it is necessary to examine anomalies on the same ASN over a long priod of time. 

This would be possible if the Search page (like the one shared above) displayed the type of anomaly as well.

More specifically, it would be a question of displaying one of the following values for anomalous Web Connectivity results:

* TCP/IP
* DNS
* HTTP-diff
* HTTP-failure

If one of the above values is displayed in each measurement, it would make looking at the types of anomalies over time (through OONI Explorer) so much easier! I personally consider this an important new feature. :)

**Comment by hellais** [comment]
Thanks for bringing this up!

I would like us to discuss if this is something which is desirable from a usability perspective and if the search page is the right place to do this.

This also requires some amount of backend work to make it work so we should first understand if it's desirable to show this information at this level.

I have flagged it as a UX and discuss type issue.

**Comment by agrabeli** [comment]
@hellais if not on the Search page, where else could this information be displayed? I think it would make going through anomalous measurements so much easier (rather than having to open individual anomalous measurements one by one). Perhaps we could consider adding a **Web Connectivity filter option** in the Search page, which allows users to filter anomalous measurements based on the `dns`, `tcp_ip`, `http-failure`, `http-diff` values.

**Comment by fortuna** [comment]
This would be very helpful in helping us understand the type of blocking and whether the results are consistent at a glance.

@hellais there's no need to change the backend. Exposing the `blocking_type` is a big improvement, and that's already available from the API. We could consider a second version where we expose more (like "blocking page/TCP reset/etc")

It seems we need to add blocking_type to the ResultItem here: https://github.com/ooni/explorer/blob/0a2fdfa358e5e7563ea807a7326eb564a4f7cddc/components/search/ResultsList.js#L362
Then change the HTML here: https://github.com/ooni/explorer/blob/0a2fdfa358e5e7563ea807a7326eb564a4f7cddc/components/search/ResultsList.js#L259

**Comment by hellais** [comment]
I made a mockup for how this could be done here: https://github.com/ooni/explorer/issues/432#issuecomment-841250387

**Comment by fortuna** [comment]
Awesome, thanks! When can we expect to see this change in production?

**Comment by sarathms** [comment]
@fortuna this was deployed to production today.
