### ISSUE TITLE
Add support for filtering all measurements globally based on a single URL (and, eventually, set of URLs)

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#443]
One of the most frequently asked questions is:

"Where around the world is my site (or a site I care about) blocked?"

It would be great to add support for filtering all measurements globally in order to find results for a single URL.

I realize though that there are challenges related to implementing this, as it would require very database-heavy queries.

**Comment by hellais** [comment]
This is a duplicate of this epic: https://github.com/ooni/explorer/issues/389
