### ISSUE TITLE
Add support for filtering IM test results based on "anomalies"

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#444]
Since the metadata of IM tests has been ingested by the pipeline, perhaps we need to add support to OONI Explorer for filtering IM test results based on "anomalies" (in the same way that we filter Web Connectivity results based on anomalies)?

**Comment by hellais** [comment]
This cannot be done until we are keeping the fastpath tables otherwise it will only work for the last 2 days or so.

I am lowering the priority and adding that issue as a blocker.

**Comment by agrabeli** [comment]
This has already been implemented since a while, so I'm closing this ticket.
