### ISSUE TITLE
Header on the countries page is not reponsive in mobile-view

### ISSUE THREAD

**Issue by NidhiKJha** [ooni/explorer#446]
## Expected Behavior
In desktop view the Countries-header is responsive ie- It displays the continents and search .

![Screenshot from 2020-03-28 01-30-16](https://user-images.githubusercontent.com/39872794/77795545-b9ec5c80-7093-11ea-8bc4-b0a9aef0c9e8.png)

## Actual Behavior
In mobile-view it is not the same. All continent names are not visible and so is the search

![Screenshot_20200325-004523](https://user-images.githubusercontent.com/39872794/77795692-ff108e80-7093-11ea-99b4-f517773cc2b9.png)

## Steps to Reproduce the Problem

  1. Click on `Countries`
 
## Specifications

  - Platform: mobile

**Comment by NidhiKJha** [comment]
Possible solutions: 
1. Decrease the font size in mobile-view
2. Make it scrollable
3. Create a dropdown

@hellais @sarathms   Which method would you recommend would be the best in this case?

**Comment by hellais** [comment]
Thanks for bringing this up!

I will see if I can put some time to make a mockup and suggest some improvements to this in the next 2 week sprint.

**Comment by hellais** [comment]
Took longer than expected, but I came up with a mock for how we could make this responsive.

I also made some small tweaks to the non-responsive version of the navbar:

![Screenshot 2020-04-24 at 12 50 51](https://user-images.githubusercontent.com/424620/80205108-60436780-862a-11ea-82d5-aaf454b91a49.png)

**Comment by hellais** [comment]
I assigned this to @sarathms who did the review of the PR from @NidhiKJha
