### ISSUE TITLE
ndt7 measurements not shown in explorer

### ISSUE THREAD

**Issue by bassosimone** [ooni/explorer#453]
Example of measurement: https://explorer.ooni.org/measurement/20200425T092838Z_AS30722_kUaRDdtR2jpHzL3kvO70ZUNzCy49xHgBuJQkIlTA35XzQOFe42

Corresponding API: https://api.ooni.io/api/v1/measurements?report_id=20200425T092838Z_AS30722_kUaRDdtR2jpHzL3kvO70ZUNzCy49xHgBuJQkIlTA35XzQOFe42

Corresponding result: https://api.ooni.io/api/v1/measurement/temp-fid-0025ccb18a8b7f1d7d40373c52f7e365

This is part of our efforts of expanding our measurement methodology. Specifically, this is a bug that appeared after we started running more ndt7 tests (i.e. NDT tests using the improved v7 methodology).

**Comment by bassosimone** [comment]
@sarathms can we close this issue now?

**Comment by sarathms** [comment]
Yes. This has been merged to the release branch. If it doesn't get closed when I merge to master, I'll manually close this.
