### ISSUE TITLE
Domain field validation passes for invalid domains

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#457]
For example if you filter by `google.com/` it passes the validation, yet produces no results.

Here is an example:
![Screenshot 2020-04-30 at 18 59 18](https://user-images.githubusercontent.com/424620/80738094-c5a8c400-8b14-11ea-9590-222f411b4f16.png)

**Comment by majakomel** [comment]
I tried to reproduce, but this seems to be resolved now.

**Comment by hellais** [comment]
Yes you are right, I think we can consider this issue solved.
