### ISSUE TITLE
Convert all copy strings into keys

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#46]
Similarly to the mobile app copy we should make all the strings into keys and put them inside of a spreadsheet so that @agrabeli can write copy for them (and also support translating them).

See: https://docs.google.com/spreadsheets/d/1GPkr_OyNhXJRTXnseyNbo2P4Du-i_W9kJdqjZG4HVkM/edit#gid=0

**Comment by gabelula** [comment]
@hellais Who can do this ticket?

**Comment by sarathms** [comment]
The keys are being collected in [this spreadsheet](https://docs.google.com/spreadsheets/d/1QAeDVF5wYj7bnTE6rJ0XX3C8sBF0o6A0TxeLw9fpTvM/edit#gid=0)

The original strings are being retained for reference to help editing the copy. Feel free to drop the column if required after the exercise.
