### ISSUE TITLE
Define some user stories for social media sharing

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#462]
This is about defining some set of user story for how people are going to make use of the social media sharing feature.

**Comment by kronaemmanuel** [comment]
https://docs.google.com/document/d/1Ni03sP62RiftWsotM4haQBfN6Lx-aijmmFaAveosYrE/edit?usp=sharing

I've discussed some user stories and ideas in this document.

**Comment by hellais** [comment]
Maybe it could be a good idea to start from the sharing and image generation for an individual measurement.

I made some hypothesis of how this could be presented in a twitter card image. It's also maybe useful just to highlight the information to be presented and the hierarchy of it.

Here are some iterations on this:
![Measurement Share.png](https://images.zenhubusercontent.com/58442543b9dc3c622022e97d/e2ecf054-859c-4f3b-b64f-7e4a9db54d89)![Measurement Share-v2.png](https://images.zenhubusercontent.com/58442543b9dc3c622022e97d/382d2300-69c9-43cd-a3da-e822f115c707)

**Comment by hellais** [comment]
I added a few more user stories to the doc

**Comment by hellais** [comment]
I would say we have a good starting point for user stories:

User Stories:
As an OONI Probe user, I want to share on social media a measurement I just ran showing evidence of censorship.
As an OONI Probe user, I want to share on social media a set of measurements I just ran
As an OONI Explorer, I want to share on social media an overview of internet censorship in a given country
As a user, I want to share OONI pages/charts on social media
As a user, I want to download OONI charts


I say we can close this issue.
