### ISSUE TITLE
Create page to try out the new Aggregation API

### ISSUE THREAD

**Issue by sarathms** [ooni/explorer#463]
@FedericoCeratto has published an aggregation API endpoint. This needs to be integrated into explorer. We will start with a separate unpublished page that queries the API for different kinds of data and renders charts based on that data. Eventually these charts or stats will make their way into country pages and other parts of the site.

**Comment by hellais** [comment]
I made small experiment for this here: https://codesandbox.io/s/nivobar-extra-layers-pbgg4?file=/src/index.js

**Comment by sarathms** [comment]
Closing this issue in favor of #474 where we implement this same thing with a mockup.
