### ISSUE TITLE
Present "valid domain" message when domain is entered with backslash

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#468]
A community member shared the following feedback:

1) If you enter the domain name incorrectly in the search field like this "http://www.gayvideo.ru/", OONI Explorer gives you a proper warning like the one shown in the scan below:

![explorer-1](https://user-images.githubusercontent.com/8290574/81582994-02947680-93b1-11ea-8810-c587f8dc4573.png)

2) If you enter the domain name up properly like this "www.gayvideo.ru",  OONI Explorer shows you the measurements:

![explorer-2](https://user-images.githubusercontent.com/8290574/81583102-248df900-93b1-11ea-82a3-3d4f4894f99a.png)

3) There is a third scenario when you can enter the domain name properly but forget to remove the backslash at the end of the URL like this"www.gayvideo.ru/" Then OONI Explorer does not give you any warnings, outputs right away "No results found" message and suggest to play with the filters to get better results. The filters in the last two examples stay the same - the only element that varies is the backslash "/"

![explorer-3](https://user-images.githubusercontent.com/8290574/81583168-3bcce680-93b1-11ea-8d5b-99263fab6c71.png)

Maybe you can tweak the settings of the Explorer to give researchers warning when they enter the domain name with a backslash.

**Comment by majakomel** [comment]
Closing this ticket since the issue seems to be resolved. If we need any more adjustments to the validation let's create a new ticket.
