### ISSUE TITLE
Remove tested since in explorer country page

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#482]
@FedericoCeratto mentioned that we will remove the             `"first_bucket_date": first_bucket_date,` key from the private API call: https://api.ooni.io/api/_/country_overview?probe_cc=IT, because it's expensive to compute.

We should therefore drop this from the UI of OONI Explorer.

**Comment by sarathms** [comment]
This should also be changed in the `description` meta tag for the country page in the work that @kronaemmanuel is doing (ref: https://github.com/ooni/explorer/pull/430/files?file-filters%5B%5D=#diff-7dac4ce12e01a5950e8a3f839aaaa15bR28-R44)
