### ISSUE TITLE
Use transient props in styled-components to get rid of DOM warnings

### ISSUE THREAD

**Issue by sarathms** [ooni/explorer#487]
Components extended using `styled-components` pass through the props we use for conditional styling (e.g `isOpen`) down to the underlying DOM triggering warnings in the browser console. This has been addressed in `styled-components@v5.1.x` by providing [transient props](https://styled-components.com/docs/api#transient-props) which are consumed by SC and won't be passed down.

As a prerequisite, **we have to upgrade `styled-components`**, which was not always very smooth.

Here's one place where this happens: [CollapseTrigger.js](https://github.com/ooni/explorer/blob/master/components/CollapseTrigger.js#L9)
There are probably one or two other places where this happens.

**Comment by DevRishiJain** [comment]
I am a beginner can you guide me about this isseu.

I want to work on it
