### ISSUE TITLE
Add support for showing "measurement is still being processed"

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#49]
When a measurement has been submitted to a collector, but is still being processed by the pipeline we should be able to show that in the explorer measurement pages.

This is related to: https://github.com/ooni/probe/issues/816

**Comment by sarathms** [comment]
@hellais Do API responses reflect this status? I haven't tried a measurement that satisfies this criteria.

**Comment by hellais** [comment]
No this is currently not supported in the pipeline and will not be done by
the time of stable launch.

**Comment by hellais** [comment]
We may actually not even need to do this anymore with the fastpath as the results are going to be available as soon as the test is complete.

Would you say this is accurate @FedericoCeratto?

**Comment by hellais** [comment]
Now measurements are published almost immediately after upload.

I say we can close this issue.
