### ISSUE TITLE
Inaccurate text displayed in comparison to test result in WhatsApp measurements

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#494]
Some measurements seem to display inaccurate text in comparison to the test result and measurement data.

For example, see this WhatsApp measurement: https://explorer.ooni.org/measurement/20200927T053618Z_AS57293_SZU6APrRIoL4pcWrIwmACx7ewQRL5pCqy5tEztueu4Tc5THkeX

It says that everything is OK, but the banner is orange (and says "anomaly") and the raw data says that connections to the registration service failed.

Perhaps logic hasn't been added to map the text with cases when connections to the registration service fail?

**Comment by bassosimone** [comment]
I just visited the OONI Explorer link above. I see it says that "Registration: Failed" in the yellow box. I am failing to understand what would be the desired behaviour: @agrabeli what am I missing here?

**Comment by msaaddev** [comment]
@agrabeli the link is not working so I can't see the issue. Can you please provide me with the correct URL so I can take solve this issue? Thanks!

**Comment by majakomel** [comment]
I'm closing this issue since the link doesn't work anymore and seems like similar problem hasn't been reported recently. In case issue appears again we can create a new ticket with recent examples.
