### ISSUE TITLE
Some measurements display the ASN in the report ID / OONI Explorer measurement URLs, but not in the raw data

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#495]
In some measurements (for example in WhatsApp and Telegram test results) the ASN is annotated as AS0, but it is possible to retrieve the actual ASN from OONI Explorer measurement URLs.

For example, in this measurement I can see from the measurement URL that the ASN is AS57293 (even though it is annotated as AS0 in the raw data): https://explorer.ooni.org/measurement/20200927T053618Z_AS57293_SZU6APrRIoL4pcWrIwmACx7ewQRL5pCqy5tEztueu4Tc5THkeX

Why does the measurement say AS0, while an ASN is displayed in the measurement URL?

**Comment by bassosimone** [comment]
The measurement linked above does seem to have AS0. Yet, the AS is not zero for the `resolver_asn`. This could either be because the lookup failed for the ASN or because there is a bug in the probe. I'm going to investigate that now.

**Comment by agrabeli** [comment]
Thanks @bassosimone for investigating this!

It's weird though that the resolver ASN would be displayed in the OONI Explorer URL -- didn't we normally have the probe ASN there? cc' @sarathms

**Comment by bassosimone** [comment]
@agrabeli yes, this is not what should happen. I believe we cannot exclude that issues with the probe are causing this. I am going to chase this issue later today, try and came out with an explanation for it. I'll ask @sarathms for help if stuck.

**Comment by bassosimone** [comment]
(Yesterday, I learned that `github.com/ooni/probe-{android,cli,ios}` does not allow the user to opt-out of including the country code into the report &mdash; and rightfully so, because omitting the country code makes a measurement unworkable! So, I am going to align `miniooni` with the other implementations for consistency.)

**Comment by bassosimone** [comment]
Releases containing the above fixes:

- [ ] https://github.com/ooni/probe-engine/releases/tag/v0.18.0
- [ ] https://github.com/ooni/probe-cli/releases/tag/v3.0.8
- [ ] desktop
- [ ] ios
- [ ] android

**Comment by bassosimone** [comment]
As mentioned above, we've rolled out explorer changes mitigating this issue. We also are rolling out mobile apps that fix this issue. We are also making progress with a new Desktop app release (with some road bumps, tho).

**Comment by bassosimone** [comment]
We're also preparing a blog post where we describe this issue. We also have in the pipeline the release of Probe Desktop 3.0.4, which will include the fixes. I would say we have done enough to mitigate this issue for now.

**Comment by bassosimone** [comment]
I'm going to close this issue. As stated above, immediate mitigation and fixing was done and we have a clear path ahead with specific issues that say what we should do (or discuss) next.
