### ISSUE TITLE
Fix error annotation in Web Connectivity measurements

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#498]
A data analyst at the Citizen Lab highlighted that many OONI Web Connectivity measurements display an "error" annotation (instead of the "anomaly" annotation). 

For example, see: https://explorer.ooni.org/measurement/20191118T063541Z_AS15802_ocKS0RbSg8GE1oLahQKYeAozvsxM3HglG8f3xMRkrWVOd4ajtN?input=http://gayguide.net/

It seems that this failure is annotated due to a failure on the control. However, the raw data clearly shows that a blockpage was served on the local network.

How can we circumvent cases when the control fails, but there is a clear sign of blocking on the local network? 

This may be possible in countries like Indonesia, where block pages are served and we have their fingerprints.

**Comment by agrabeli** [comment]
This bug seems to be caused because OONI Explorer presents an error, irrespective of whether there is a known block. 

In cases like Indonesia or UAE, where they serve block pages and we have their fingerprints, it would be great if we can find a way to circumvent the control failure and display "confirmed blocked" nonetheless.

This though should probably happen in the API analysis logic, since OONI Explorer merely fetches measurements from the OONI API.

**Comment by bassosimone** [comment]
This seems an issue with the pipeline. When processing or reprocessing a measurement the pipeline _should_ check whether the body contains a known fingerprint regardless of whether the control measurement failed.

**Comment by agrabeli** [comment]
I am migrating this ticket over to the backend repo.
