### ISSUE TITLE
Replace momentjs as a dependency

### ISSUE THREAD

**Issue by sarathms** [ooni/explorer#510]
The momentjs team has [announced](https://momentjs.com/docs/#/-project-status/) that they consider it to be a legacy project in maintenance-only mode. We may not need to replace it immediately. But we should understand the implications for us and evaluate the way forward. Some useful reads before we discuss this:
- https://inventi.studio/en/blog/why-you-shouldnt-use-moment-js
- https://dockyard.com/blog/2020/02/14/you-probably-don-t-need-moment-js-anymore
- https://blog.logrocket.com/4-alternatives-to-moment-js-for-internationalizing-dates/

**Comment by hellais** [comment]
This has been done, we might revisit it in light of the new date picker component.
