### ISSUE TITLE
Communicate to users that OONI Explorer measurements are by default limited to the last 30 days

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#511]
Now that we've switched over to a new database, OONI Explorer will be adapted to only display measurements (in the Search page) by default (when users click "Filter") based on the past 30 days (since it relies on the API -- which has made this change).

We therefore need to clearly communicate this to our users.

Below is an example, to help explain my point:

When filtering the Burundi page of OONI Explorer based on `www.facebook.com` we get: https://explorer.ooni.org/search?until=2020-10-27&domain=www.facebook.com&probe_cc=BI

^^ This displays all `www.facebook.com` measurements from the last month, up until 28th September 2020.

The problem with this page is that it doesn't indicate in any way that more measurements (from previous dates) actually exist, leading the user (me) to believe that these are the only `www.facebook.com` measurements that have ever been collected from Burundi.

However, this assumption is wrong, and the only reason why I realized it was because I happened to write a report (https://ooni.org/post/2020-burundi-blocks-social-media-amid-election/) earlier this year on the blocking of `www.facebook.com` in Burundi.

When I filtered OONI Explorer Burundi search results with a date range set to 1st to 31st May 2020 (which is when facebook.com was blocked in Burundi), I get the relevant measurements showing blocking: https://explorer.ooni.org/search?until=2020-05-31&domain=www.facebook.com&probe_cc=BI&since=2020-05-01

Most users though will probably not think to do this, which is why I propose the following fixes:

1. At the end of the results (https://explorer.ooni.org/search?until=2020-10-27&domain=www.facebook.com&probe_cc=BI) when the **date range is not specified**, display a message at the end, such as the following: **The above measurements are limited to the last month. To find older measurements (collected during previous months/years), please specify the date range in the filters on the left of this page.**

2. When the relevant domain has not been tested over the last month (such as www.facebook.com in Uganda, which has been tested in the past, but not over the last month: https://explorer.ooni.org/search?until=2020-10-26&domain=www.facebook.com&probe_cc=UG), **instead of displaying "Results not found"**, display something like the following message: 

**This domain has not been tested in the selected country over the past month. Please explore all measurements on the testing of this domain [link to relevant query].** 

**If you don't get results, it's likely the case that that domain hasn't been tested in this country yet. If you're in that country, you can try testing that domain through the use of [OONI Probe](https://ooni.org/install/).**

@sarathms @hellais What do you think?

**Comment by hellais** [comment]
I think this should be solved with a very simple UI fix:

1. Adding the `from` to the last month in the URL
2. Filling out by default the from field in the form

I believe this is already done.
