### ISSUE TITLE
Replace the version number in the footer with the commit hash of deployed version

### ISSUE THREAD

**Issue by sarathms** [ooni/explorer#521]
The purpose is to reduce the dependency on the need to update version number every time the app is deployed. This makes it easier to deploy automatically in a CI/CD pipeline if necessary. The git commit has is a sufficient reference to the code that is deployed.

![image](https://user-images.githubusercontent.com/700829/112211853-ab774900-8bf2-11eb-98e8-e140de491faf.png)

**Comment by msaaddev** [comment]
@sarathms are we looking to integrate the deployed version's commit hash or the latest release's one? Also, is the master branch being the one that is deployed? Like any update to the master will update the main website?

**Comment by hellais** [comment]
This has been done
