### ISSUE TITLE
Add two-dimensional charts to MAT

### ISSUE THREAD

**Issue by sarathms** [ooni/explorer#536]
This is the leftover task from #528 

- [ ] Add support for axis_y plotting
- [ ] One heatmap each for anomaly_count and confirmed_count
- - [ ] Build upon that a single heatmap with both values in each cell
- [ ] Show blocked websites in tabular form

**Comment by hellais** [comment]
The top priorities for the user stories are:
* One row per domain, bar chart in each cell
* One row per probe_asn, fixed input

**Comment by hellais** [comment]
This is done.
