### ISSUE TITLE
Facebook Messenger page should present reason for blocking

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#545]
I think that how OONI Explorer interprets the reason for blocking in the facebook_messenger test result is wrong.

Take for example the following measurement: https://explorer.ooni.org/measurement/20210204T015900Z_facebookmessenger_MM_133385_n1_QRW5HRxhJVlfmpoX

The relevant test_keys are:
```
"facebook_dns_blocking":true
"facebook_tcp_blocking":false
```

This should be interpreted by OONI Explorer as "Blocking method = DNS" and not that the TCP endpoints have failed.

As a result I recommend refactoring the facebook messenger page to work similarly to the web_connectivity page where it displays the blocking reason right under the text saying `Facebook Messenger is likely blocked` and using the same strings we use for the web_connectivity results.

When `facebook_dns_blocking` is set to `true` then we should display "DNS Blocking", when `facebook_tcp_blocking` is set to `true` then we should display "TCP/IP based blocking"

**Comment by agrabeli** [comment]
Oh, this is an important bug! :/ @sarathms can we prioritize this?

**Comment by hellais** [comment]
It looks like the main bug doesn't exist anymore, we should I guess just improve the view of the facebook messenger page to look more like the web connectivity page.

Specifically:
* Place the blocking reason in the heading using this component: https://github.com/ooni/explorer/blob/master/components/measurement/nettests/WebConnectivity.js#L501
* Use the same component we use in the web connectivity page to display successful or failing tcp connect results
