### ISSUE TITLE
Show progress indicator when navigating between pages

### ISSUE THREAD

**Issue by sarathms** [ooni/explorer#55]
Something on the lines of [this example](https://github.com/zeit/next.js/blob/master/examples/with-loading/pages/_app.js).

**Comment by sarathms** [comment]
Added in df2e590

**Comment by elioqoshi** [comment]
Is this live @sarathms?

**Comment by sarathms** [comment]
Yes it is live on https://explorer-beta.ooni.io
![image](https://user-images.githubusercontent.com/700829/56303251-8c6c0480-6109-11e9-8a1d-c96b591e0bcb.png)

But you might have to suggest a better color for the loading bar.

**Comment by hellais** [comment]
Yeah I think we should go for some other color as blue on blue barely visible. @elioqoshi @holantonela what do you think?

**Comment by elioqoshi** [comment]
> Yeah I think we should go for some other color as blue on blue barely visible.

Yeah, let's go with the anomaly color (Yellow 9 ) for the loading bar.

**Comment by hellais** [comment]
I have deployed this to: https://explorer-beta.ooni.io/.

@elioqoshi check if it looks good and if so close this issue.

**Comment by elioqoshi** [comment]
LGTM! Closing
