### ISSUE TITLE
Link to MLab data in the country pages

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#569]

**Comment by msaaddev** [comment]
@hellais can you explain this issue a little bit, please.

**Comment by hellais** [comment]
This issue is a little bit tricky. Basically, we used to have network performance indicators in the country pages, yet we removed it because we had no good way of keeping it in sync. This issue is mostly about doing the research to understand what we should be linking in the country page, while we work on resuming the sync of performance data from MLab.

**Comment by hellais** [comment]
I reached out to the folks at M-Lab and they suggest we don't link to pages on the M-Lab website as the links are going to soon change, but rather we work on integrating OONI Explorer with their new API: https://statistics.measurementlab.net/.

I left some further questions for them related to how we could go about doing this integration and I will update relevant issues as I get more information.

**Comment by hellais** [comment]
It looks like we are not going to be linking to a specific page after all, but rather focus on doing the proper integration of M-Lab data into the country pages (see: https://github.com/ooni/backend/issues/180).

I am going to document in ooni/backend#180 the Q&A I had about this with folks from M-Lab.
