### ISSUE TITLE
Add support for linking to measurements in MAT

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#572]
When you click on a bar chart, you can access directly the measurements they pertain to. This can be achieved by linking to the relevant OONI Explorer search query.

**Comment by hellais** [comment]
This is not done.

**Comment by hellais** [comment]
We can make it so that when you click on a given bar the tooltip becomes fixed and that way you can click inside of the tooltip container the link to the measurements. While the specific bar is selected, it should be highlighted and there should be a close icon in the top right corner of the tooltip.

**Comment by sarathms** [comment]
This is done in #618 and deployed to the [test instance](https://explorer.test.ooni.org/experimental/mat?since=2021-10-17&until=2021-11-09&test_name=web_connectivity&axis_x=measurement_start_day&axis_y=category_code).
