### ISSUE TITLE
Add missing copy in RiseupVPN OONI Explorer measurements

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#576]
While RiseupVPN measurements are annotated based on `ok` and `anomaly`, they're missing relevant copy. For example, see: https://explorer.ooni.org/measurement/20210416T134431Z_riseupvpn_SG_206092_n1_uWBStMToLoaoOg0n

We therefore need to add the copy in RiseupVPN measurements on OONI Explorer.

**Comment by sarathms** [comment]
I have made the necessary changes. The copy needs to be reviewed and updated before deploying.
