### ISSUE TITLE
Country list: tighten up the padding

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#58]
I think the padding and spacing in the country list is too much and I would suggest making it a bit tighter.

![Screenshot 2019-03-26 at 14 27 19](https://user-images.githubusercontent.com/424620/55017526-3831a100-4ff1-11e9-9452-0f58a1bcba03.png)

Ideally we would manage to fit a region inside of a page.

See for example the apple choose your country page (which the country list was inspired by):
![Screenshot 2019-03-26 at 14 29 49](https://user-images.githubusercontent.com/424620/55017610-5d261400-4ff1-11e9-82a9-43f9d1f4764b.png)

cc @elioqoshi @holantonela

**Comment by sarathms** [comment]
Improved this a bit in 96bf492. Will wait for more comments before more development.

**Comment by hellais** [comment]
To me this looks good. @holantonela @elioqoshi do you agree the padding is better now?

**Comment by holantonela** [comment]
Looks good for me. @elioqoshi?

**Comment by elioqoshi** [comment]
The page looks perfect to me as well, thanks!

**Comment by hellais** [comment]
I am looking at the country listing page and I still have the impression the padding is still a bit too much.

I find that bumping it down from the current `32px` `margin-top, margin-bottom` down to `8px` makes it more usable:

![Screenshot 2019-04-26 at 18 15 13](https://user-images.githubusercontent.com/424620/56821725-67853900-684f-11e9-99e0-10ac55caf02b.png)
![Screenshot 2019-04-26 at 18 15 24](https://user-images.githubusercontent.com/424620/56821726-681dcf80-684f-11e9-8306-aa5d954d1ee8.png)

@elioqoshi @holantonela what do you think?

**Comment by elioqoshi** [comment]
@hellais I see what you mean. I think 8px is a bit too tight though. Let's do 16px? That will make the horizontal and vertical spacing similar I think.

**Comment by hellais** [comment]
> That will make the horizontal and vertical spacing similar I think.

tbh I find the horizontal spacing too lax as well, but it works there because in any case we can't get more than 4 countries to fit horizontally given their current size.

OTOH saving up on vertical space can allow us to fit a whole extra row of countries by reducing it to 8px, which is why I was suggesting it.

**Comment by holantonela** [comment]
I removed the margin-bottom style on cards, and I got this grid. I think it is the right balance for the grid.

![image](https://user-images.githubusercontent.com/7602174/59217979-905e5500-8b95-11e9-9607-f14dbb3eddf9.png)

**Comment by sarathms** [comment]
Alternatively I reduced the margin on top and bottom by proportional amount, effectively getting the exact same gap. This way the horizontal and vertical spacing between the cards, and the padding inside the cards are all the same (16px).

![image](https://user-images.githubusercontent.com/700829/59223638-69565200-8b9a-11e9-9e82-98fedb91b6a8.png)

**Comment by holantonela** [comment]
Looks good for me!
