### ISSUE TITLE
Error page leaks internal webservice URL

### ISSUE THREAD

**Issue by bassosimone** [ooni/explorer#588]
When we access a nonexistent measurement (e.g., https://explorer.ooni.org/measurement/20210517T170752Z_dash_IT_30722_n1_WkDTRvZQpiVwEjL9), the error page includes the address of the internal `127.0.0.1:3000` service. Maybe we should not show that?

**Comment by sarathms** [comment]
This was fixed in #587 and just went live. Thanks for reporting.
