### ISSUE TITLE
Display failed measurements as "Failure" on OONI Explorer listing (rather than as "Accessible")

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#590]
When measurements fail, they are currently listed in the OONI Explorer Search page as "Accessible" (green), even though the measurement pages themselves show that the measurement failed. This is misleading, and can result in users not inspecting failed measurements (assuming that they're OK) which, in some cases, may actually contain signs of potential blocking (if, for example, the "failure" is due to a heuristics issue/limitation). 

This is an example shared by community members:

![image (11)](https://user-images.githubusercontent.com/8290574/118967496-13d07580-b96b-11eb-81a4-85bcc986b342.png)

In the OONI Explorer listing, these measurements are annotated as "accessible", but if you open each individual measurement, you will see that they actually failed.

We should therefore annotate failed measurements as "**Failure**" in the OONI Explorer listing, and perhaps annotate them with the color gray (instead of green), similarly to the color used in the headers of failed measurement pages.

**Comment by fortuna** [comment]
In terms of implementation, this should be straightforward, since the data needed is already available in the UI from the API. It should be a change similar to the one that started showing the anomaly types.

**Comment by fortuna** [comment]
This could be a good bug for external contributors.

**Comment by agrabeli** [comment]
Here are some other examples of faulty measurements (from Turkmenistan):

https://explorer.ooni.org/measurement/20211030T070225Z_webconnectivity_TM_20661_n1_a4Mmz4unMl2V9OAx?input=http%3A%2F%2Ffteproxy.org%2F
https://explorer.ooni.org/measurement/20211030T070225Z_webconnectivity_TM_20661_n1_a4Mmz4unMl2V9OAx?input=https%3A%2F%2Fwww.rbc.ru%2F
https://explorer.ooni.org/measurement/20211030T070225Z_webconnectivity_TM_20661_n1_a4Mmz4unMl2V9OAx?input=https%3A%2F%2Frus.azattyq.org%2F

^^ These measurements are annotated as "errors" (connection_refused), but are listed as "Accessible" in the OONI Explorer Search listing.

**Comment by agrabeli** [comment]
Link to listing: https://explorer.ooni.org/search?since=2021-02-01&until=2021-05-31&domain=psiphon.ca&probe_cc=BY&probe_asn=AS42772

**Comment by hellais** [comment]
This has been fixed in OONI Explorer as we now hide by default all failed measurements and we display them consistently between the search listing and the measurement pages.

I believe this can now be considered done.

**Comment by fortuna** [comment]
The problem with hiding the measurements is that some "failures" are actually good measurements with bad evaluation. It's still helpful to see them in the Explorer. What need to fix are:
- The evaluation of the measurement (not show Failure when we can determine what happened)
- Make sure what's shown in the listing matches what's shown in the measurements (not show "Accessible" when it's a failure)

**Comment by fortuna** [comment]
Also, seeing the failures is a good way to find issues or bugs with the measurements.
