### ISSUE TITLE
Link to OONI Explorer GitHub repo in OONI Explorer

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#591]
Community members mentioned that it can be challenging to find which OONI GitHub repo to open a ticket on (given that we have so many repos), and that it would be helpful if we link to the OONI Explorer repo (https://github.com/ooni/explorer/issues/) inside OONI Explorer, so that they can easily open tickets and share feedback.

**Comment by fortuna** [comment]
I'm also happy to use the feedback tool. That's even easier but unfortunately it's not currently working.

**Comment by sarathms** [comment]
As I was deploying an unrelated change today, I included a link to this repository in the footer. I had not seen this issue by then. I can point it directly to the issues page in the next update.

@fortuna I opened an issue for the feedback tool problem here https://github.com/ooni/explorer/issues/593.

**Comment by hellais** [comment]
This is done, we now have a link in the footer.
