### ISSUE TITLE
Feedback reporting tool is broken

### ISSUE THREAD

**Issue by sarathms** [ooni/explorer#593]
The floating button in the corner is broken because adblockers have started blocking CORS requests to Sentry. This change (https://github.com/easylist/easylist/commit/13eabc59ec3b45a92f603f98da08abf4d3bbab81) seems to be the one that has brought this into effect. 

This blocking prevents sentry from showing the UI built into the SDK. Further investigation needed to check if regular crash reports to Sentry are also broken.

Possible solutions to consider (starting with most preferred):
1. Put together a native mechanism to let users share feedback that doesn't depend on 3rd party services. This can then be piped to somewhere more prominent like a private slack channel for better visibility.
2. If other error reporting API calls to Sentry are not blocked, then build a form to collect feedback and continue reporting via Sentry. This could the quicker solution.
3. Take the user to Github issues page. This is only better than deciding to not have this feature at all.

Thank you @fortuna for reporting this.

**Comment by hellais** [comment]
This is happening because adblockers will block requests going to sentry. The correct fix would be to setup a relay towards sentry so that we can overcome adblocking issues.

**Comment by majakomel** [comment]
Not relevant anymore, closing.
