### ISSUE TITLE
add support for the .foundation TLD

### ISSUE THREAD

**Issue by bassosimone** [ooni/explorer#605]
Explorer currently does not accept as filtering URL the https://lgbt.foundation domain name.

**Comment by hellais** [comment]
It appears that the regexp we use for domain names has a limit to the maximum length the tld can be set to 7: https://github.com/ooni/explorer/blob/master/components/search/FilterSidebar.js#L220.

I think we should change this regexp to be a bit more lax and support any arbitrarily long tld.

**Comment by bassosimone** [comment]
sounds good to me

**Comment by hellais** [comment]
It appears that the [regexp used on the citizenlab/test-lists repo](https://github.com/citizenlab/test-lists/blob/master/scripts/lint-lists.py#L20) also does not consider `lgbt.foundation` as a valid domain name, so we should update that regexp as well.
