### ISSUE TITLE
Add support for marking as failed measurements that have an inconsistent timestamp

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#625]
The basic requirement is to ensure we present these results as failed. Even better would be if we had the ability to indicate in the UI that the **reason** for them being failed is that they have an inconsistent measurement_start_time.

**Comment by sarathms** [comment]
This was added in #627 (2790b236111168345ed0d5c7372d91f63f1db0ba). Such measurements now marked as `failure` in the API and we display the message in `scores` at the top of the page.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/700829/145641213-d7c9e2a5-b4c9-43f5-863a-ac58c9917017.png">
