### ISSUE TITLE
Inconsistency between search listing and measurement page for some measurements

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#626]
Some measurements are listing as confirmed in the search listing, but then are marked as failure inside of the measurement page.

An example of such measurement is the following: https://explorer.ooni.org/measurement/20211118T114400Z_webconnectivity_IR_44244_n1_CBR1LoUbZI6eWPs4?input=http%3A%2F%2Fgawker.com%2F.

I can see from the API response that the reason for this being marked as failure is that it comes from the future: https://api.ooni.io/api/v1/measurement_meta?report_id=20211118T114400Z_webconnectivity_IR_44244_n1_CBR1LoUbZI6eWPs4&input=http://gawker.com/.

I think this issue should be fixed by ensuring that the logic for marking something as confirmed, anomaly or failure is aligned between the measurement page and search listing. In this particular case the issue is that the search listing is giving precedence to the confirmed flag, while the measurement page is giving preference to the failure flag.

The correct behaviour should probably be to favour the failure flag and display a failure in the listing as well.

**Comment by sarathms** [comment]
> the issue is that the search listing is giving precedence to the confirmed flag, while the measurement page is giving preference to the failure flag

I agree that this should be made consistent across both contexts.

In which case, we should cover other similar cases and come up with an order of precedence for Explorer to use wherever it applies. The proposed solution will work when we want to ensure that failed measurements are shown as failed. For example, how do we then handle this:
```
failure: false,
confirmed: true,
anomaly: true
```

I think the larger problem is the boolean-based state model. Is there a reason why we send a combination of flags to determine the state instead of sending
```typescript
state: 'anomaly' | 'confirmed' | 'failure' | 'accessible' | 'down' | '720p' | '1080p (HD)' ... `
```

This will make it much easier to practice the principle that decision-making on Explorer should be minimal.

**Comment by hellais** [comment]
> For example, how do we then handle this:

I think the order of precedence should be: `failure`, `confirmed`, `anomaly`. Confirmed comes before anomaly, because in the current model a `confirmed` case is a special case of `anomaly`.

> I think the larger problem is the boolean-based state model. Is there a reason why we send a combination of flags to determine the state instead of sending

I think this is a valid point and it would possibly also help us in resolving this issue we have in the aggregation metrics: https://github.com/ooni/backend/issues/486.

I would like to hear from @FedericoCeratto how much effort he thinks it would be to implement this in the API.

**Comment by FedericoCeratto** [comment]
Evaluating `failure`, `confirmed`, `anomaly` in this order in Explorer is correct.
`failure`, `confirmed`, `anomaly` is already a simplified model for backward compatibiilty. `scores` contains more information and is growing over time. Adding a new API return value involves future maintenance effort and we should discuss it in a meeting.
