### ISSUE TITLE
Improvement to the navbar stickiness

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#63]
Another thing to think about post-beta is how we handle the stickiness of the navbar and the navigation items that are inconsistent between the country list and the country page.

We discussed with @sarathms that it would be nice to also have the section headers in the country list go into the sticky navbar as you scroll down.

It's also I think especially important for the country page to include the country name in the navbar as that makes it more useful when taking a screenshot.

![Screenshot 2019-03-26 at 18 07 03](https://user-images.githubusercontent.com/424620/55017941-1e448e00-4ff2-11e9-9200-9b688301726d.png)

I also think that for consistency the navbar in the country page should follow the pattern of that in the country listing. It would also save us some precious horizontal space.

cc @elioqoshi @holantonela

**Comment by hellais** [comment]
These react components may be useful:
https://github.com/yahoo/react-stickynode
https://react-sticky.netlify.com/#/stacked
https://lxieyang.github.io/blogs/tech-2018-08-18-reactstrap-gatsby-auto-hiding-navbar-trick/

**Comment by hellais** [comment]
I think that the same should also be done for in the country listing for the "Search for countries" and "Jump to section" nav bars.

cc @holantonela @elioqoshi

**Comment by elioqoshi** [comment]
In the new full width mockup, the country name is aligned to the left:
https://www.figma.com/file/Z6PtVLW7YkqcTRIRsO2Qzg/Explorer-Country-Pages?node-id=1394%3A13

I'd suggest that once scrolled down, the country name and flag replaces the OONI Explorer logo in order to be visible on the sticky navbar.

**Comment by holantonela** [comment]
I made a suggestion at https://github.com/ooni/explorer/issues/71. We could have this pattern across the entire site.

**Comment by hellais** [comment]
This is now done.
