### ISSUE TITLE
Explain why some countries don't render "Confirmed" results

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#636]
During the OONI Partner Training 2021, participants mentioned that they found it confusing why with some countries, when they filtered results based on "Confirmed", they got no results and just a 500 error message (whereas the "All results" and "Anomalies" filters worked).

When users select "Confirmed" for a country where we have no automatically confirmed blocked cases, we should communicate this with a message (instead of just presenting an error message). This probably first requires relevant backend work, as well as relevant copy for communication.

**Comment by hellais** [comment]
This was a backend database issue, which is now resolved since we have moved over to the new clickhouse based API.

Closing.
