### ISSUE TITLE
Open search page results in a new tab

### ISSUE THREAD

**Issue by sarathms** [ooni/explorer#64]
By opening the result in the same tab, we lose the context and if/when the user goes back to the search results, they have to wait for the search query to fetch the same results again.

**Comment by hellais** [comment]
I think this is a UX question that @elioqoshi and @holantonela should think of.

Let push this to post-beta.

**Comment by holantonela** [comment]
Opening results in a new tab is not a common pattern for search engines. We can think about how to improve the search page for that mentioned scenario. For instance, we could show previous searches or we can allow users to save favorite queries for searches.
I don't think this is an issue we should handle on this release, tho.

**Comment by hellais** [comment]
Yeah I agree with @holantonela with it being a bit unusual to open search results in new tabs.

The past search is a good idea, maybe we can rename this issue as that and push it to post launch?

**Comment by hellais** [comment]
Perhaps we should then close this issue as wontfix?

**Comment by hellais** [comment]
Please reopen if you think it's necessary
