### ISSUE TITLE
Fix bounding boxes of nav bar entries

### ISSUE THREAD

**Issue by sarathms** [ooni/explorer#65]
## Expected Behavior
Menu items should be clickable only on the item's content.

## Actual Behavior
The margins between menu items are clickable too.

**Comment by hellais** [comment]
Which nav bar is this referring to?

**Comment by elioqoshi** [comment]
I suppose the main nav bar is meant here. I agree with Sarath on this one. I'd suggest a similar behaviour with how GitHub nav bar works (Pull Requests, Issues, Marketplace, Explore): https://github.com/

**Comment by sarathms** [comment]
This was fixed 65ce6aa

**Comment by hellais** [comment]
@elioqoshi @holantonela can you look at this and if it's good close it?

**Comment by holantonela** [comment]
Is good.
