### ISSUE TITLE
Application error when entering dates via manual entry

### ISSUE THREAD

**Issue by anadahz** [ooni/explorer#651]
## Expected Behavior

Change date range by keyboard input.

## Actual Behavior

Application error.

## Steps to Reproduce the Problem

  1. Go to the search menu and enter a date range with a keyboard input

## Tested

- Mozilla Firefox
- Tor Browser

## Demo

https://user-images.githubusercontent.com/4969544/150033854-16f57508-0a40-4d5f-9bba-ed227737e28d.mp4

**Comment by hellais** [comment]
Thanks for reporting this issue. It was previously reported over here: https://github.com/ooni/explorer/issues/633, so I am going to close this as a duplicate.
