### ISSUE TITLE
Search by `input` and `domain`

### ISSUE THREAD

**Issue by sarathms** [ooni/explorer#655]
The current search page doesn't allow linking from MAT for specific `input` values like `https://styles.redditmedia.com/robots.txt`

## Expected Behavior
Search page should allow looking up by specific URL (a.k.a `input`). This is [supported by the API](https://api.ooni.io/apidocs/#/default/get_api_v1_measurements). 

## Actual Behavior
Currently, the search page filter is restricted to using domain names and the underlying API calls are made with parameters like `domain=ooni.org`.

**Comment by majakomel** [comment]
@hellais @sarathms This issue seems to be invalid by now since both MAT and search interface are filtering only based on `doman`,  not `input` anymore. Can you confirm?

**Comment by sarathms** [comment]
I think we want to be able to choose one of the two (domain, input). There are some backend changes needed to support this. Maybe @hellais can clarify.
