### ISSUE TITLE
Ability to search for country in Country list page

### ISSUE THREAD

**Issue by sarathms** [ooni/explorer#66]
This is in the mockup but hasn't been implemented yet.

**Comment by sarathms** [comment]
Added in 8b569109090adcfa02e4cde119a1f29afe515d75

**Comment by hellais** [comment]
This looks good to me. @elioqoshi @holantonela can you take a look?

**Comment by elioqoshi** [comment]
Search looks and works as intended. Thanks! This can be closed I'd say.
