### ISSUE TITLE
mat: user feedback for improvements to the MAT

### ISSUE THREAD

**Issue by xhdix** [ooni/explorer#661]
1. is it possible to have an hourly chart instead of a daily chart within a day or a week?
2. this is painful, each time I should disable it: https://github.com/ooni/explorer/blob/4ab5bf48508cceb9b21b4e68c2f9e17f5816fafe/components/aggregation/mat/Resizable.js#L12
3. have input value also in the box (it's useful when we want to take screenshots)

**Comment by majakomel** [comment]
All of those have been done since the issue has been created, closing.
