### ISSUE TITLE
Rename the options under the "X Axis" and "Y Axis" filters on the MAT

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#667]
Currently the "X Axis" and "Y Axis" filters on the MAT include the following options in the drop-down menu:

- `measurement_start_day`
- `input`
- `category_code`
- `probe_cc`
- `probe_asn`

However, these labels might be super confusing for users. For example, it might not be clear to a journalist who tries to use the MAT that `probe_cc` means "Country", or that `probe_asn` means "ASN". As a result, they'd end up having a hard time using the MAT to find the data they care about.

I therefore propose that we **rename these labels** to the following:

- [x] Replace `measurement_start_day` with `Measurement start day`
- [x] Replace `input` with `Input`
- [x] Replace `category_code` with `Website category codes`
- [x] Replace `probe_cc` with `Countries`
- [x] Replace `probe_asn` with `ASN`

**Comment by daredevilteja** [comment]
hi @hellais @agrabeli I am interested in contributing to this project. Can I fix this issue?

**Comment by sarathms** [comment]
This was done in #724 (135ea9110f61e3167b82f63b5a10d05ae8f4f546)
