### ISSUE TITLE
Rename "Category codes" to "Website category codes" on the MAT

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#668]
It's worth clarifying on the MAT that "category codes" are only relevant to Web Connectivity measurements (and that users cannot expect to filter based on category codes for other tests).

I therefore propose editing the copy of "Category codes" to "Website category codes" on the MAT.

**Comment by sarathms** [comment]
This was renamed to `Website Categories` in #724 (135ea9110f61e3167b82f63b5a10d05ae8f4f546)
