### ISSUE TITLE
Inform users that they can only filter based on "category codes" (MAT) when they have selected Web Connectivity

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#669]
If a user selects a category code (e.g. ENV) and a non-Web Connectivity test (e.g. WhatsApp), they get the following type of notification when they click "Filter":

![error](https://user-images.githubusercontent.com/8290574/155356414-feaab698-887b-44ce-a07a-fc1a5d96be4a.png)

This notification wrongly tells the user that "there isn't enough data", whereas the problem is actually that they shouldn't select a category code when filtering by a test other than Web Connectivity. 

I therefore propose adding the following message when a user filters by a category code and a non-Web Connectivity test result:

_**Category codes are only applicable to website testing. Please select the Web Connectivity test and try again.**_ 

Alternatively, this problem could be fixed if the "Category codes" option *only* appears if Web Connectivity is selected. That would be the easiest for users too, I think.

**Comment by majakomel** [comment]
This has been done: https://github.com/ooni/explorer/pull/752
