### ISSUE TITLE
Inform users that they need to have selected "Web Connectivity" when filtering by URL in the MAT

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#671]
Similarly to what is mentioned in https://github.com/ooni/explorer/issues/669, when users add a URL under `input` in the MAT and select a test type other than Web Connectivity, they get the following message:

![error-2](https://user-images.githubusercontent.com/8290574/155358762-e1b3c009-c9b2-493b-aa51-db149ee710c8.png)

This notification wrongly tells the user that "there isn't enough data", when in fact the problem is that they can't filter by URL unless "Web Connectivity" is selected under `Test Name`. 

I therefore propose adding the following message when a user filters by a URL and a non-Web Connectivity test result:

**Please select the Web Connectivity test to filter measurements based on a URL.**

Alternatively, would it be possible to ensure that "Web Connectivity" is automatically selected when a user tries to filter by a URL?

**Comment by sarathms** [comment]
As part of #724, we made some such filters conditional (4fc041799ebb65b03066d962cf680dd24cd5a45b). So `Input` (now called `Domain`) is shown only if `Web Connectivity` is selected.
