### ISSUE TITLE
Fix display of dates when large date ranges are selected on the MAT

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#679]
When I filter the MAT based on a relatively large date range (e.g. https://explorer.ooni.org/experimental/mat?probe_cc=MM&test_name=whatsapp&since=2018-01-24&until=2022-02-24&axis_x=measurement_start_day), it is impossible to view the dates on the Y axis:

![blurry-dates](https://user-images.githubusercontent.com/8290574/155370171-3ef810a0-b8ce-4e96-a5a6-2c8232c18786.png)

Can we please fix this?

**Comment by hellais** [comment]
The charts and API isn't really designed to scale to that level. I think in the interim we can either explicitly disallow plotting charts for a time window larger than say 1 year or just accept this as something that can happen.

**Comment by GermaVinsmoke** [comment]
How about we look for a way to make charts horizontally scrollable?

**Comment by GermaVinsmoke** [comment]
Shows undefined

Case - https://explorer.ooni.org/experimental/mat?probe_cc=AF&test_name=web_connectivity&since=2022-02-16&until=2022-03-19&axis_x=measurement_start_day

![image](https://user-images.githubusercontent.com/32815509/158985352-d955ef5d-0129-4a27-a594-420dc06a4297.png)

**Comment by sarathms** [comment]
As part of #724 we added a confirmation dialog (18cb119) when a longer time duration is selected. Additionally, we also reduced the number of dates shown in the xAxis (dd52273).
