### ISSUE TITLE
Add support for logging of exceptions

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#68]
I think it's useful, especially while developing, to log stacktraces using sentry.

This will allow us to have all the exceptions aggregated in a single place which makes following up on bugs easier.

The integration of sentry is mostly painless (at least it was in golang and for other js projects) see: https://github.com/zeit/next.js/tree/master/examples/with-sentry.

@sarathms I have sent you an invite to join the #ooni team on sentry, when you accept it you should be able to get all the necessary tokens to set it up (and also view exceptions).

**Comment by hellais** [comment]
Here is the relevant code snippet suggested by sentry:
```
import * as Sentry from '@sentry/browser';

// Sentry.init({
//  dsn: "https://49af7fff247c445b9a7c98ee21ddfd2f@sentry.io/1427510"
// });
// should have been called before using it here
// ideally before even rendering your react app 

class ExampleBoundary extends Component {
    constructor(props) {
        super(props);
        this.state = { error: null };
    }

    componentDidCatch(error, errorInfo) {
      this.setState({ error });
      Sentry.withScope(scope => {
        Object.keys(errorInfo).forEach(key => {
          scope.setExtra(key, errorInfo[key]);
        });
        Sentry.captureException(error);
      });
    }

    render() {
        if (this.state.error) {
            //render fallback UI
            return (
              <a onClick={() => Sentry.showReportDialog()}>Report feedback</a>
            );
        } else {
            //when there's not an error, render children untouched
            return this.props.children;
        }
    }
}
```

**Comment by sarathms** [comment]
This was implemented some time back. I pulled it back from review stage because I wanted to check:
[ ] Sentry alerts are triggered in production
[ ] Console messages are not garbled in development mode

**Comment by sarathms** [comment]
This seems to work as expected as of now.
