### ISSUE TITLE
fix: remove console logs in the explorer

### ISSUE THREAD

**Issue by thara003** [ooni/explorer#680]
There are few console logs in the production server and I think it's not a good idea to have those.

## Expected Behavior
No console logs in the production server

## Actual Behavior
Here, we can see a few console logs in the  production server 

![image](https://user-images.githubusercontent.com/79561774/155764108-b331529d-62ec-494e-94d3-c88af60489e7.png)

## Steps to Reproduce the Problem

  1. Go to [explorer search ](https://explorer.ooni.org/search?since=2022-01-26&until=2022-02-26&failure=false&probe_cc=AT&test_name=facebook_messenger)
  2. Open Console from there and you can see the console log
  
## Specifications

  - Version: Windows 11
  - Platform: Windows

**Comment by majakomel** [comment]
Resolved in https://github.com/ooni/explorer/pull/710
