### ISSUE TITLE
Implement a better date picker

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#689]
Currently we have a date picker component that requires two interactions to select a date range.

It would be great if we switched to something that allowed the user to select a range in a single interaction and possibly also specify the range as something like "last X days".

It's important that what we choose supports the ability to also specify the start and end date by typing into the field the timestamp.

**Comment by Mohamed-Ayaan358** [comment]
![image](https://user-images.githubusercontent.com/72858215/161677283-686bc71c-e690-431b-b8df-32c23cc71383.png)
Is this the relevant date time picker that we are discussing in this issue?
