### ISSUE TITLE
Whole Error object displayed to user on experimental/mat page

### ISSUE THREAD

**Issue by GermaVinsmoke** [ooni/explorer#704]
## Expected Behavior
I think it'll be better to show a message saying that "Nothing was found..."

## Actual Behavior

In case of error, the whole error is being displayed to the user, not sure if a user really wants to see something like this while searching.

![image](https://user-images.githubusercontent.com/32815509/158420949-c7cdd0d4-134d-473c-b35c-9382baba7fb9.png)

## Steps to Reproduce the Problem

  1. Used these search query terms - http://localhost:3100/experimental/mat?test_name=dash&since=2022-02-13&until=2022-03-16&axis_x=domain&axis_y=domain

## Specifications

  - Version: On this commit - 9ef08a4a5601ab7b013224a167ae635d6f453b10
  - Platform: Windows 10
  - Subsystem: Not sure what this is.

**Comment by majakomel** [comment]
Error handling and display has been improved since, this is how it looks now: 

<img width="1299" alt="Screenshot 2022-05-13 at 17 43 47" src="https://user-images.githubusercontent.com/3431279/168319573-5c959177-2b31-4213-99ee-fdde19f67c1d.png">
