### ISSUE TITLE
Navigation bars in country list and country page

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#71]
I think we could come up with a better pattern for displaying the navigation bars inside of the country list and country pages.

The issue I see with the current solutions is that they are inconsistent across the two pages and I would like us to see if we can use a similar pattern used in the country list for the country page.

The pages in question are the following:
![Screenshot 2019-04-10 at 12 10 03](https://user-images.githubusercontent.com/424620/55870772-98941700-5b89-11e9-9d06-6b2c70cbd73f.png)
![Screenshot 2019-04-10 at 11 58 02](https://user-images.githubusercontent.com/424620/55870776-9af67100-5b89-11e9-99f9-2879859ba2fe.png)

The pattern we pick should work in a way where it can be "sticky" on top.

cc @holantonela

**Comment by holantonela** [comment]
Yes. Let's unify the navigation pattern there. The sub nav should remain sticky at the top on both places, the Countries List and inside the Country page. 

On the country pages, we can merge the country flag into the submenu, and make both sticky. See here:

![37](https://user-images.githubusercontent.com/7602174/55901898-b28d2400-5ba0-11e9-850b-3c476ae89b19.gif)

We may need to remove the left sidebar and extend the main content to 100%.

![Country Page - Sub Nav](https://user-images.githubusercontent.com/7602174/55900929-a7d18f80-5b9e-11e9-9214-f96d5e9a078b.png)
![Country Page - Scrolled](https://user-images.githubusercontent.com/7602174/55900928-a7d18f80-5b9e-11e9-8b78-210ec67c1342.png)

For the Country List, the continent's submenu could look like: 

![Country List - Sub Nav](https://user-images.githubusercontent.com/7602174/55900927-a738f900-5b9e-11e9-89e4-4410db912a58.png)


📎 Figma File 
https://www.figma.com/file/K1NGidHqUldfVuDNmU4MnO/Explorer-Navigation-Menues?node-id=296%3A1786

**Comment by hellais** [comment]
@holantonela yes I like this!

Can we perhaps also make it so the country name is visible when you scroll down?

**Comment by holantonela** [comment]
If we keep the country code? I'm afraid that the country name is very long. We could try both tho.

![Country Page - Scrolled](https://user-images.githubusercontent.com/7602174/55954936-6db3cc80-5c36-11e9-96d6-00ea3d2d0bdc.jpg)

**Comment by hellais** [comment]
> @holantonela If we keep the country code? 

Yes I think that works great. It's mostly so that when people take screenshots or have scrolled down into the page they can remember what they are on.

The flag + the country name should be pretty intuitive and surely unambigous, so it should work fine.

@sarathms do you think this doable as part of explorer-beta or should we put it in the post-beta milestone?

**Comment by sarathms** [comment]
I think this cannot be included in the beta milestone, to avoid a rush job. There is a chance that I can pick up a couple of items from post-beta bucket before we release it as beta. Will try and include this if possible.

**Comment by elioqoshi** [comment]
I am working on the mockup of this right now and expect to finish it next week. Agree with what Sarath said.

**Comment by elioqoshi** [comment]
Kinda related to: https://github.com/ooni/explorer/issues/63

**Comment by hellais** [comment]
Ah yes this does appear to be a duplicate of: https://github.com/ooni/explorer/issues/63.

Are we aiming to do this as part of Beta or post beta?

**Comment by elioqoshi** [comment]
I'd suggest post-beta. This does not look like a dealbreaker rather than an improved viewing experience.

**Comment by elioqoshi** [comment]
Mockups of the full width country page here:
https://www.figma.com/file/Z6PtVLW7YkqcTRIRsO2Qzg/Explorer-Country-Pages?node-id=1394%3A13

**Comment by hellais** [comment]
This is now done.
