### ISSUE TITLE
Add Highlights copy to Transifex 

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#715]
The copy under the "Highlights" section of the OONI Explorer homepage is currently untranslated (for example, see: https://explorer.test.ooni.org/fa) because that copy hasn't been added to Transifex (https://www.transifex.com/otf/ooni-explorer/) for translation. 

![highlights-untranslated](https://user-images.githubusercontent.com/8290574/160179890-7d4b0a51-09c8-489d-8265-64b09ce46b63.png)

We therefore need to add the copy from all the boxes of the "Highlights" section to strings that are uploaded to Transifex (and therefore translated by the Localization Lab community).

Similarly, the last sentence of the OONI Explorer homepage is untranslated and needs to be added to the copy in Transifex. See:

![last-sentence-explorer](https://user-images.githubusercontent.com/8290574/160180366-5e63ed10-69f5-4a83-8f7f-747ef6905d53.png)

**Comment by majakomel** [comment]
This has bene done here https://github.com/ooni/explorer/pull/824
