### ISSUE TITLE
explorer search: when switching between test names the domain filter is not reset

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#735]
When I switch from having filtered web_connectivity with a specific domain, to a test that doesn't support an input, I get an empty result.

Steps to reproduce:
* Visit: https://explorer.ooni.org/search?since=2022-02-01&until=2022-03-30&probe_cc=IR&test_name=web_connectivity&domain=edge-chat.instagram.com&probe_asn=AS44244&failure=false
* Change the test name to Tor
* See an empty result list

This doesn't happen when the only applied filter is the since,until and the domain.

**Comment by harisankar01** [comment]
There is no result list if we set the test name to anything except **Web Connectivity** with the since, until and domain filter set. can you please elaborate the problem. Thank you.
