### ISSUE TITLE
Fix bug in App Stats component lifecycle method definition

### ISSUE THREAD

**Issue by sarathms** [ooni/explorer#75]
There is a typo in `/components/country/app-stats.js` where the lifecycle method is defined as `static getDerivedStateFromprops`. However, fixing this typo exposes a bug where the component doesn't behave as expected.

**Comment by resistancecanyon** [comment]
@sarathms Isn't it safe to remove the getDerivedStateFromprops function alltogether?
The state transfer is not being used 
Only the internal state 
`      data: result.data,
      fetching: false
`
are used in this component
Besides `getDerivedStateFromprops` is now not recommended for most use cases in react.

**Comment by sarathms** [comment]
You are right. It doesn't serve any purpose anymore. It was written as part of an older UX which we dropped along the way. I checked to confirm that removing it doesn't affect anything.

**Comment by sarathms** [comment]
While this one was a trivial change (in #340), there are other places in the project where we used `getDerivedStateFromProps` which needs some careful refactoring. Opening another issue for that.
