### ISSUE TITLE
Show most measured AS number and name in Country overview

### ISSUE THREAD

**Issue by sarathms** [ooni/explorer#76]
As per mockup
![image](https://user-images.githubusercontent.com/700829/56319477-d5cf4a80-612f-11e9-8a68-0ada70a8e249.png)

This information is currently not readily available.

**Comment by hellais** [comment]
To be honest I am not entirely sure this of the usefulness of this bit of information being present in the text.

We already sort the relevant sections by the network which has the most measurements on the API endpoints.

**Comment by elioqoshi** [comment]
I do think that it's useful to explicitly state the most measured AS as it's not available information otherwise as far as I knowbut if @agrabeli and @hellais think it's not critical information, let's omit it.

**Comment by hellais** [comment]
As we are omitting this, we can close this issue.
