### ISSUE TITLE
Make the point be a cursor when hovering over the explorer logo in the header

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#78]
Currently when I hover over the OONI Explorer logo in the upper right corner there is nothing to indicate that the item is clickable.

I think we should at the very least make the cursor a point (the little hand thingy) when you hover over it and maybe also give it a subtle effect on hover.

@elioqoshi @holantonela ideas for how to make it clear you can click on the OONI Explorer logo to go back to the homepage?

**Comment by holantonela** [comment]
Yes. The entire `id="Logo"` should be an `<a>` element.

**Comment by elioqoshi** [comment]
What Arturo said is exactly what needs to be done yes.

**Comment by hellais** [comment]
This is fixed.
