### ISSUE TITLE
OONI Explorer shows website is Accessible instead of Confirmed Blocked

### ISSUE THREAD

**Issue by sloncocs** [ooni/explorer#781]
The issue was reported by @Hezo in '#ooni' public channel. 

## Expected Behavior
The test should be annotated as 'DNS anomaly' based on the raw data while it is being shown as Confirmed Blocked because the DNS response was Injected to government blockpage

## Actual Behavior
https://explorer.ooni.org/measurement/20220808T164350Z_webconnectivity_ID_17995_n1_7PEtlgE9r63GDkKU?input=http://xhamster.com 

![](https://files.slack.com/files-pri/T37Q8EGUU-F03SQ9YN1C5/image.png)

## Steps to Reproduce the Problem
—

## Specifications

  - Version: ooniprobe-desktop (3.7.0)
  - Platform: Windows
  - Subsystem:

**Comment by bassosimone** [comment]
We triaged the issue with @hellais and this turns out to be a problem in the probe engine. Therefore, I am going to close this issue in favour of the following engine-specific issue: https://github.com/ooni/probe/issues/2206.
