### ISSUE TITLE
Browser back button not working on ASN network page

### ISSUE THREAD

**Issue by GermaVinsmoke** [ooni/explorer#797]
## Expected Behavior

The network page - https://explorer.ooni.org/network/AS30969?since=2022-08-24&until=2022-09-24
Whenever we use browser back button, it should take us back to the previous page.

## Actual Behavior

1. The browser back button is not working. It's not letting me move to the previous page.

## Steps to Reproduce the Problem

  1. Open Search. Selected any report from the list present on the right side. Example - [AS30969](https://explorer.ooni.org/measurement/20220923T113758Z_webconnectivity_ZM_30969_n1_oTbjSLwtt3qMvosY?input=https%3A%2F%2Fwww.mail.com%2F)
  2. Click on AS30969 Network which will lead to the desired page.
  3. Try clicking on browsers back button.

## Specifications

  - Version: 642cddf
  - Platform: Windows 10 Chrome
  - Subsystem: -

**Comment by ishanExtreme** [comment]
Anyone working on this issue?
