### ISSUE TITLE
Reconsider the tabs for filtering by anomaly and confirmed

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#82]
Currently we use a tabbed navigation pattern for allowing users to filter through measurements by anomaly or confirmed.
![Screenshot 2019-04-18 at 15 13 06](https://user-images.githubusercontent.com/424620/56363466-974b9580-61ec-11e9-8144-e1264c8e556e.png)

In light of the fact that an anomaly or confirmed is not really a new page of the results page, but is rather just an attribute you are filtering on, I suspect it may be more suited to change these to simply be checkboxes or radio selectors in the filter section of this page.

@holantonela @elioqoshi what do you think? Do you think the use of tabs is appropriate or could we go for another solution?

**Comment by hellais** [comment]
As discussed with @sarathms we are going to aim to convert the tabs into a radio and put them into the side bar to make this view be decent on mobile.

I will move this into the beta milestone as it seems achievable to do it by then.

**Comment by holantonela** [comment]
We should consider the entire left sidebar. Could we move this for stable @hellais ?

**Comment by hellais** [comment]
I believe this is now done.
