### ISSUE TITLE
Edit prompt when URL is mystyped

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#832]
A community member highlighted that they were unable to find measurements for a particular URL (even though that URL is in the test list, and even though they're able to get measurements based on its domain), thinking that the URL filter on the OONI Explorer Search page does not work.

When we discussed this with them, we realized that the issue was that the trailing slash was missing from the end of the URL (when entered into the URL slot), resulting in OONI Explorer claiming that `No results were found`. 

This community member then proposed that we add a prompt, informing OONI Explorer users that a trailing slash should be added at the end of the URL. 

Currently, when a URL is mystyped, the following prompt appears:

```
Please enter full URL or IP address, such as https://fbcdn.net/robots.txt
```
We could edit this text to say:

```
Please enter a full URL (e.g. https://twitter.com/) with a trailing slash (`/`) or an IP address
```
We should also edit the example URL in the URL slot to be:

```
https://twitter.com/
```

**Comment by GermaVinsmoke** [comment]
This one's changed/solved in daee5f6.
