### ISSUE TITLE
Tooltips for charts are not usable

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#84]
Currently when I hover over a bar chart in the country page the tooltip is going to be cropped most of the time making the information not visible.

![Screenshot 2019-04-18 at 17 04 27](https://user-images.githubusercontent.com/424620/56370723-0aa8d380-61fc-11e9-9cfb-124d668a7023.png)

We should find a simple way to make at least all the content in them be readable.

**Comment by elioqoshi** [comment]
Could the tool tips also be styled like in the mockups? 

i.e: 
![image](https://user-images.githubusercontent.com/5436686/56371375-4c864980-61fd-11e9-983b-bd6cd48a2918.png)

**Comment by hellais** [comment]
@elioqoshi the tooltip should scale to support at least all the possible values, ie: Total, failures, confirmed, anomalies.

I think that a tooltip is not the right pattern here and I think we should probably have a fixed legend that is updated when you hover over the item.

@sarathms In looking at this bit of code I also noticed there is actually a bug in the rendering of the tooltip. You are registering a `VictoryVoronoiContainer` inside of the `VictoryChart` component. This means that the voronoi container will be triggered on all the stacked bar charts when the chart is all zeros (they are all equally distant from the mouse).

The end result is that the content of the tooltip ends up being duplicated and repeated 4 times.

I did a little bit of research into this matter and the recommended way to deal with tooltips and stacked bar charts is to register the label only on the highest item in the stack, see: https://github.com/FormidableLabs/victory/issues/997#issuecomment-399338369

**Comment by sarathms** [comment]
> bug in the rendering of the tooltip.

@hellais Additionally, that seems to be explain why the tooltip doesn't get triggered in lower parts of the graph. I clearly didn't understand what 'voronoi` means :-|

**Comment by elioqoshi** [comment]
> @elioqoshi the tooltip should scale to support at least all the possible values, ie: Total, failures, confirmed, anomalies.

I should have specified that I meant the style mostly. middle alignment for these kind of values and the container shape (which would scale depending on the content).

> I think that a tooltip is not the right pattern here and I think we should probably have a fixed legend that is updated when you hover over the item.

I do think we should have addressed these in the mockup stage. What is the issue you see with the tooltips and the information needed to be conveyed?

**Comment by hellais** [comment]
> I do think we should have addressed these in the mockup stage. 

Yeah I am sorry for not having addressed this there. It wasn't clear that you were expecting also the on hover effects to be implemented as per the mocks.

I thought we had discussed that the dynamic elements should be discussed in the implementation based on what is feasible, but perhaps that was not clear.

> What is the issue you see with the tooltips and the information needed to be conveyed?

This issue is that I don't think we can get it to fit inside of the cart component.

The tooltips are rendered inside of the SVG viewport which has a fixed height and width. How you mocked them up I think is going to be pretty complex to implement in a way that is usable.

That is why I am suggesting for a solution which is simpler to implement and possibly not too bad to see as well.

I will see if I can work a bit on this as I think the charts are a pretty important aspect of the charts.

**Comment by hellais** [comment]
So I was actually mistaken. The flyout component renders inside of a **separate** SVG container and it can be setup in such a way where it isn't cropped.

I managed to get this working properly inside of https://github.com/ooni/explorer/pull/86.

I am still not a huge fan of the tooltip style, but I think we can roll with it.

![Screenshot 2019-04-19 at 18 00 59](https://user-images.githubusercontent.com/424620/56432366-57a8aa80-62cd-11e9-824d-a3b74c222a9c.png)

With some minor tweaks I think we can get it to look close to the mocks.

**Comment by elioqoshi** [comment]
> This issue is that I don't think we can get it to fit inside of the cart component.

The tooltips are rendered inside of the SVG viewport which has a fixed height and width. How you mocked them up I think is going to be pretty complex to implement in a way that is usable.

Ah I see. That makes sense.

> I am still not a huge fan of the tooltip style, but I think we can roll with it.

Seeing as you fixed the latter to some extent, what is the issue you see here? The issue I see is information hierarchy related so namely I'd suggest to left-align the text, space out the data bit and start with the number and then the status (e.g 1 Confirmed) as that is semantically more readable.

Eventually adding colored dots for color coding the measurement status could also be done.

**Comment by holantonela** [comment]
This is done. We'll polish it in #104
