### ISSUE TITLE
MAT: crash when manually typing in time range

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#840]
Steps to reproduce:
* Go to https://explorer.ooni.org/chart/mat
* Select the "2023" part of the From field and start typing "2"
* As soon as you type "0" (following the "2") the page crashes with "Application error: a client-side exception has occurred (see the browser console for more information)."

See screen recording:

https://user-images.githubusercontent.com/424620/221208945-405e31de-e58c-44bf-81e2-233d1cc8160c.mov

**Comment by Dipanshu-Singh-Dev** [comment]
Hey hellais,
I am a front end web developer. I know React and have some experience with Next.js.
Could you please assign me this issue?

**Comment by majakomel** [comment]
Fixed in https://github.com/ooni/explorer/commit/329cc9ac9b0277cc625ed29fcc50046adb5daccf
