### ISSUE TITLE
search: display loader while the search results are being fetched

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#851]
Currently if you are on a slow network and it takes a while to perform the first load of the search results page, the page displays "No results found" while it's loading giving no indication that it's actually loading in the background.

We should instead have a loader that informs the user that the page is still being loaded.

See screenshot:
<img width="1470" alt="Screenshot 2023-04-12 at 10 04 56" src="https://user-images.githubusercontent.com/424620/231320911-4f278453-06fe-4365-8e82-c92681708d5a.png">

**Comment by majakomel** [comment]
Fixed in https://github.com/ooni/explorer/commit/c06f187dbfb5a74e561200b6158a0080009e208c
