### ISSUE TITLE
Localized OONI Explorer mobile, Search country filter bug

### ISSUE THREAD

**Issue by sloncocs** [ooni/explorer#861]
<- Remember to label this issue accordingly (bug, feature, help wanted, etc). And remove any information that does not fit the issue you are submitting.  -> 

**!! this issue can be reproduced only on mobile, the desktop version works fine**

## Expected Behavior

If the user sets the country filter to country A, the Search shows measurements collected from country A.

## Actual Behavior

If the user uses the Russian language version of OONI Explorer on mobile and uses Search, once they set the country filter to country X, the Search shows measurements collected from country X+1. This behaviour starts from ~letter B («Б»). 

Examples: 

1. I set the country filter to the Bahamas («Багамы»), but the Search results in measurements collected from Bangladesh

![IMAGE 2023-06-28 10:12:01](https://github.com/ooni/explorer/assets/16296135/e2494fb7-7c0d-4a79-bd3d-2c4e68093336)
![IMAGE 2023-06-28 10:12:06](https://github.com/ooni/explorer/assets/16296135/b891046e-67cd-4861-9611-d877e2a5ed23)

2. I set the country filter to Bahrein («Бахрейн»), but the Search results in measurements collected from Belarus

![IMAGE 2023-06-28 10:12:16](https://github.com/ooni/explorer/assets/16296135/27a43b09-37ae-4765-ac19-60bb590edc73)
![IMAGE 2023-06-28 10:12:21](https://github.com/ooni/explorer/assets/16296135/f5b517d9-db0d-4509-b039-d38de7c1ba9f)

## Steps to Reproduce the Problem

  1. Open OONI Explorer on mobile 
  2. Set up language to Russian 
  3. Open Search tool  
  4. Set the country filter to Багамы or Бахрейн 
  5. Check the results of the search

## Specifications

  - Browser: Safari 
  - Platform: iOS

**Comment by majakomel** [comment]
Closing this since it has been fixed.
