### ISSUE TITLE
MAT: when the bars are grouped by week, the search links point to the wrong page

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#864]
When I click on a bar with weekly granularity, the filter in the search is still for an individual day, while it should instead be filtering by the week.

**Comment by Schinmay31** [comment]
hey @hellais ,
I attempted to replicate issue #864 but faced challenges as a beginner. Here are my interpretations:

1.Users should access past week results via date range settings, but the result tab only shows issues from the last day.

2.When selecting weekly granularity, the date format doesn't update as expected.

I couldn't recreate these issues. Is the problem resolved, or did I misunderstand?
Your guidance is appreciated.
