### ISSUE TITLE
Bug: Domain can't be found in the Domains page

### ISSUE THREAD

**Issue by sloncocs** [ooni/explorer#866]
## Expected Behavior
The Domains page should show the measurements pertaining to 'martinoticias.com'. 

## Actual Behavior
The measurements pertaining to 'martinoticias.com' can be found through [OONI Search](https://explorer.ooni.org/search?since=2023-07-09&until=2023-08-09&failure=true&domain=martinoticias.com) and [OONI MAT](https://explorer.ooni.org/chart/mat?since=2023-07-09&until=2023-08-09&time_grain=day&axis_x=measurement_start_day&test_name=web_connectivity&domain=martinoticias.com) (see screenshots attached), but cannot be found through the search field of the Domains page. 

<img width="1032" alt="Screenshot 2023-08-08 at 13 37 23" src="https://github.com/ooni/explorer/assets/16296135/54459c99-6768-457a-b7bf-7dc37a3d1bf9">
<img width="1040" alt="Screenshot 2023-08-08 at 13 36 49" src="https://github.com/ooni/explorer/assets/16296135/6c0ffe54-dc10-4c4b-8b33-634c91ecaa82">
<img width="1035" alt="Screenshot 2023-08-08 at 13 37 10" src="https://github.com/ooni/explorer/assets/16296135/464ad48e-abae-4807-a06b-7f946d7c889a">

## Steps to Reproduce the Problem

  1. Search for 'martinoticias.com' on https://explorer.ooni.org/domains

**Comment by hellais** [comment]
The URL is not in the test-lists. In order for a domain to appear in the domains page it needs to be in the test-lists.
