### ISSUE TITLE
Improve responsiveness

### ISSUE THREAD

**Issue by sarathms** [ooni/explorer#87]
The pages have been developed with very little effort towards responsiveness. It seems to be much easier than anticipated to make most of the site viewable on smaller screens. Listing out specific actions that can help achieve this goal:

- [x] Use arrays to define widths for grid components e.g `<Box width={[1, 1/2]}>` across the site.
- ~Collapse the sidebars in search and countries pages into a hamburger menu on smaller screens~
- [x] Turn on `responsive={true}` on VictoryContainer components that render charts.
- ~Explore usage of `vw` (viewport width) notation to specify font sizes or alternatively use modules like [react-textfit](https://www.npmjs.com/package/react-textfit)~ #181

**Comment by holantonela** [comment]
@elioqoshi do you have mockups to attach to this ticket as a reference? Thanks!

**Comment by elioqoshi** [comment]
The usual ones from Figma.

Landing Page: https://www.figma.com/file/OElUj1XR5SmbXUpWVzl8iton/Explorer-Landing-Page?node-id=0%3A1

Country Page and Measurement Page: https://www.figma.com/file/Z6PtVLW7YkqcTRIRsO2Qzg/Explorer-Country-Pages?node-id=1319%3A1136

**Comment by holantonela** [comment]
Thanks @elioqoshi. I think the Search page is missing. Do we have it somewhere? Thanks!

**Comment by elioqoshi** [comment]
It's the XD file: https://design.ooni.io/mockups/explorer

Although we did a lot of changes live and not on the mockups afterwards.

**Comment by sarathms** [comment]
> Collapse the sidebars in search and countries pages into a hamburger menu on smaller screens
Countries page sidebar is being redesigned in #63 

@holantonela Do we want to do something for the search page sidebar on mobile?

**Comment by sarathms** [comment]
> Turn on responsive={true} on VictoryContainer components that render charts.
This is being worked upon in #104 #167

**Comment by sarathms** [comment]
> Explore usage of vw (viewport width) notation

Opended #181 to handle this later.

**Comment by sarathms** [comment]
Closing this as the items discussed here are now being tracked in their own issues.
