### ISSUE TITLE
CIRP: Move display of ASNs from country heading to lower field

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#887]
When ASNs are added through the Censorship Incident Reporting Platform (CIRP), they are currently displayed in the same heading as the country (as illustrated below):

<img width="629" alt="asn-test" src="https://github.com/ooni/explorer/assets/8290574/4edc09c9-d5a3-445b-9761-b2e91e43555e">

There are 2 main issues with this:
1) We're highlighting information (ASNs) which doesn't communicate much to the target audience of this platform, as most journalists and human rights defenders don't know what an ASN is
2) If we want to include a long list of ASNs (which would be the case in countries like Russia), it would look strange from a UI perspective displaying a long list of ASNs next to the country name

As a result of the above, I have refrained from including ASNs in all of the reports that I have published so far. This is a shame though, as there is value in including ASNs (e.g. linking relevant reports to network-specific pages based on ASNs).

I therefore would like to propose that the ASNs are not displayed alongside the country name, but are instead moved further below (in a smaller font), perhaps alongside other fields (such as tags, test names, etc.).

**Comment by majakomel** [comment]
This has been resolved before the release:

<img width="735" alt="Screenshot 2024-01-24 at 16 12 14" src="https://github.com/ooni/explorer/assets/3431279/76fc9460-fc90-4a95-849a-9fe52d567a3c">
