### ISSUE TITLE
Finish the footer component

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#9]
We currently have a very flashy footer component, but the links are not pointing anywhere.

It would be great if @elioqoshi (and maybe @agrabeli) were to come up with what should actually be inside of the footer and where the various links should point to.

Here is how the footer currently looks like:

![screen shot 2018-08-01 at 18 00 08](https://user-images.githubusercontent.com/424620/43533298-c691659a-95b4-11e8-8c1a-c46ea7c794a5.png)

For every item in the footer we need to know what it should be linking to.

**Comment by elioqoshi** [comment]
We never actually disucssed what the footer content should be. Consider it more of a layout as it is right now and depending on what we think is most suitable, we can alter it. It would be good to get input from @agrabeli on what would be best relevant here.

Also is there a way to show only reports on the websites without the generic blog?

**Comment by sarathms** [comment]
This has been implemented as part of #53

**Comment by hellais** [comment]
This looks good to me. @elioqoshi @holantonela @agrabeli can you also take a look?

**Comment by elioqoshi** [comment]
Looks good to me apart the OONI logo.

![image](https://user-images.githubusercontent.com/5436686/56358049-c27ab880-61dd-11e9-96e9-0085abb7be0b.png)


The light background logo has been used. We need to use the dark background logo

**Comment by holantonela** [comment]
- [ ] At http://explorer-beta.ooni.io the `FAQ` link is `#`
- [ ] The OONI logo could go to the top
- [ ] `Global community measuring internet censorship around the world` needs a . at the end
- [ ] `© 2018 Open Observatory of Network Interference (OONI)` should say `2019`
- [ ] `Content available under a Creative Commons license` should link to https://github.com/ooni/license

**Comment by sarathms** [comment]
> At http://explorer-beta.ooni.io the FAQ link is #
Do we have an FAQ? I couldn't find anything. @hellais @agrabeli 

> The OONI logo could go to the top
@holantonela Can you elaborate this?

**Comment by hellais** [comment]
@elioqoshi @holantonela can you look at this and if it's good close it?

**Comment by sarathms** [comment]
@holantonela has already seen this and approved on Slack. The pending item is the missing target for the **FAQ** link. I have requested @agrabeli to provide a link.

**Comment by holantonela** [comment]
@hellais opened #107 to define that link. I'll close this issue then.
