### ISSUE TITLE
Fix overlap of tooltips in the country overview

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#90]
As mentioned by @sarathms in https://github.com/ooni/explorer/pull/86.

> the tooltips for the two charts in the svg now overlap at most places

In the case I used as an example they weren't overlapping as much, but I can definitely see how if the data is quite stationary the tooltips can overlap quite often.

I would say that we deal with it by either:
* Making some tweaks to the style and positioning of the networks tooltip (ex. we don't need to repeat the date in there and we can bottom align it)
* Consolidate all the info just one tooltip

I prefer the first option because keeping the tooltips separate we are teaching the user what the line graph means.

cc @holantonela @elioqoshi

**Comment by elioqoshi** [comment]
> Making some tweaks to the style and positioning of the networks tooltip (ex. we don't need to repeat the date in there and we can bottom align it)

I agree with this too. I could walk through it and fix it with @sarathms probably?

**Comment by sarathms** [comment]
I think I have figured out how to achieve this. Implemented something like that for the landing page charts [here](https://github.com/ooni/explorer/pull/92/commits/9346d67e70b83affb641084122bd9fb13ca14039#diff-3afb32e375548ef2747f1a89357f9febR71)
![image](https://user-images.githubusercontent.com/700829/56949599-595e4380-6b01-11e9-9e71-e261816d250c.png)

This a single tooltip rendered for two line charts rendered inside a single `VictoryChart`. I discovered while debugging something else that the tooltips contain enough context (e.g name) to help us control them better.

**Comment by sarathms** [comment]
One problem with the above mentioned fix is that we lose the pointer on both tooltips. To avoid that we can orient the two tool tips in opposite directions.

![Screenshot from 2019-06-24 13-25-21](https://user-images.githubusercontent.com/700829/60038952-99662080-9683-11e9-803a-5030f135486f.png)

**Comment by hellais** [comment]
Yeah I think this solution works.

**Comment by hellais** [comment]
This is fixed by https://github.com/ooni/explorer/pull/205
