### ISSUE TITLE
Multi-platform: Improve mobile views for certain pages 

### ISSUE THREAD

**Issue by jbonisteel** [ooni/explorer#951]
As part of the multi-platform project, we will likely want to use web views for the measurement detail views. There will be some work required to make them more mobile friendly, this is a placeholder epic for this work.

**Comment by sdsantos** [comment]
If we can possibly load the page without enabling javascript, it would also be a win in terms of security for us. Currently we use it to Download the raw JSON and collapse/expand sections.
