### ISSUE TITLE
Mat page not displaying modal when too long intervals are chosen

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#955]
In the past when you picked a too long interval we showed a modal telling the user that a too big time interval was picked.

Now the background is darkened but the modal doesn't appear, making it not possible to display large time intervals in MAT.

I suspect this has something to do with the tailwind related refactor.

See screenshot:
![Screenshot 2024-08-28 at 10 23 04](https://github.com/user-attachments/assets/9ab0e970-5854-47c4-b731-d54202bf9b2f)

**Comment by majakomel** [comment]
Fixed in https://github.com/ooni/explorer/commit/1fbbefbd5c3b65426d9fbc3047e9a21fa44bd996
