### ISSUE TITLE
Add effect to Explorer primary button on landing page

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#97]
I think the button on the landing page could use with some effect on hover and on click.

![Screenshot 2019-05-02 at 12 23 25](https://user-images.githubusercontent.com/424620/57069542-2e2c4d80-6cd5-11e9-9494-6d24b3c91234.png)

Maybe have the content of the button become filled with more white and make it darker on click?

@holantonela @elioqoshi what do you think?

**Comment by holantonela** [comment]
Yes, it should work like https://getbootstrap.com/docs/4.0/components/buttons/#outline-buttons

**Comment by holantonela** [comment]
@sarathms you right. Lets link it to /countries. @hellais @agrabeli what do you think?

**Comment by hellais** [comment]
Yeah I think linking it to the country listing is good.

**Comment by elioqoshi** [comment]
> Yes, it should work like https://getbootstrap.com/docs/4.0/components/buttons/#outline-buttons

Exactly, agreed.
