### ISSUE TITLE
[bug] OONI Explorer Countries interface doesn't allow to search in languages other than English

### ISSUE THREAD

**Issue by sloncocs** [ooni/explorer#975]
## Expected Behavior

When a localised version of OONI Explorer is used, the user should be able to use the search field in the chosen language. For example, if I set OONI Explorer's language to Russian and open Countries page, I expect to search for the countries' names in Russian (as they are shown in Russian within the interface)

## Actual Behavior

Here is an example of how it worked for me with the Russian interface, I am trying to look for Tajikistan: 
<img width="1136" alt="Screenshot 2024-11-21 at 17 25 06" src="https://github.com/user-attachments/assets/1d9f3326-70be-4020-b2c9-f271ddc7ae2f">
<img width="1124" alt="Screenshot 2024-11-21 at 17 25 12" src="https://github.com/user-attachments/assets/a9fa4838-f43c-4109-af13-6819d49e15d5">

**Comment by majakomel** [comment]
Fixed in https://github.com/ooni/explorer/commit/714dfb003e3fe02ce1ee4949209c8b7bb8b13cbb
